/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.resources.ats.jobs.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum JobsScreeningQuestionsListRequestExpandItem {
    JOB("job"),

    OPTIONS("options");

    private final String value;

    JobsScreeningQuestionsListRequestExpandItem(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
