/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.chat.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.merge.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExternalTargetFieldApiResponse.Builder.class)
public final class ExternalTargetFieldApiResponse {
    private final Optional<List<ExternalTargetFieldApi>> user;

    private final Optional<List<ExternalTargetFieldApi>> group;

    private final Optional<List<ExternalTargetFieldApi>> conversation;

    private final Optional<List<ExternalTargetFieldApi>> member;

    private final Map<String, Object> additionalProperties;

    private ExternalTargetFieldApiResponse(
            Optional<List<ExternalTargetFieldApi>> user,
            Optional<List<ExternalTargetFieldApi>> group,
            Optional<List<ExternalTargetFieldApi>> conversation,
            Optional<List<ExternalTargetFieldApi>> member,
            Map<String, Object> additionalProperties) {
        this.user = user;
        this.group = group;
        this.conversation = conversation;
        this.member = member;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("User")
    public Optional<List<ExternalTargetFieldApi>> getUser() {
        return user;
    }

    @JsonProperty("Group")
    public Optional<List<ExternalTargetFieldApi>> getGroup() {
        return group;
    }

    @JsonProperty("Conversation")
    public Optional<List<ExternalTargetFieldApi>> getConversation() {
        return conversation;
    }

    @JsonProperty("Member")
    public Optional<List<ExternalTargetFieldApi>> getMember() {
        return member;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ExternalTargetFieldApiResponse && equalTo((ExternalTargetFieldApiResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ExternalTargetFieldApiResponse other) {
        return user.equals(other.user)
                && group.equals(other.group)
                && conversation.equals(other.conversation)
                && member.equals(other.member);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.user, this.group, this.conversation, this.member);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ExternalTargetFieldApi>> user = Optional.empty();

        private Optional<List<ExternalTargetFieldApi>> group = Optional.empty();

        private Optional<List<ExternalTargetFieldApi>> conversation = Optional.empty();

        private Optional<List<ExternalTargetFieldApi>> member = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ExternalTargetFieldApiResponse other) {
            user(other.getUser());
            group(other.getGroup());
            conversation(other.getConversation());
            member(other.getMember());
            return this;
        }

        @JsonSetter(value = "User", nulls = Nulls.SKIP)
        public Builder user(Optional<List<ExternalTargetFieldApi>> user) {
            this.user = user;
            return this;
        }

        public Builder user(List<ExternalTargetFieldApi> user) {
            this.user = Optional.ofNullable(user);
            return this;
        }

        @JsonSetter(value = "Group", nulls = Nulls.SKIP)
        public Builder group(Optional<List<ExternalTargetFieldApi>> group) {
            this.group = group;
            return this;
        }

        public Builder group(List<ExternalTargetFieldApi> group) {
            this.group = Optional.ofNullable(group);
            return this;
        }

        @JsonSetter(value = "Conversation", nulls = Nulls.SKIP)
        public Builder conversation(Optional<List<ExternalTargetFieldApi>> conversation) {
            this.conversation = conversation;
            return this;
        }

        public Builder conversation(List<ExternalTargetFieldApi> conversation) {
            this.conversation = Optional.ofNullable(conversation);
            return this;
        }

        @JsonSetter(value = "Member", nulls = Nulls.SKIP)
        public Builder member(Optional<List<ExternalTargetFieldApi>> member) {
            this.member = member;
            return this;
        }

        public Builder member(List<ExternalTargetFieldApi> member) {
            this.member = Optional.ofNullable(member);
            return this;
        }

        public ExternalTargetFieldApiResponse build() {
            return new ExternalTargetFieldApiResponse(user, group, conversation, member, additionalProperties);
        }
    }
}
