/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.resources.accounting.transactions;

import com.merge.api.core.ClientOptions;
import com.merge.api.core.RequestOptions;
import com.merge.api.resources.accounting.transactions.requests.TransactionsListRequest;
import com.merge.api.resources.accounting.transactions.requests.TransactionsRetrieveRequest;
import com.merge.api.resources.accounting.types.PaginatedTransactionList;
import com.merge.api.resources.accounting.types.Transaction;
import java.util.concurrent.CompletableFuture;

public class AsyncTransactionsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawTransactionsClient rawClient;

    public AsyncTransactionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawTransactionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawTransactionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a list of <code>Transaction</code> objects.
     */
    public CompletableFuture<PaginatedTransactionList> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Returns a list of <code>Transaction</code> objects.
     */
    public CompletableFuture<PaginatedTransactionList> list(TransactionsListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Returns a list of <code>Transaction</code> objects.
     */
    public CompletableFuture<PaginatedTransactionList> list(
            TransactionsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>Transaction</code> object with the given <code>id</code>.
     */
    public CompletableFuture<Transaction> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>Transaction</code> object with the given <code>id</code>.
     */
    public CompletableFuture<Transaction> retrieve(String id, TransactionsRetrieveRequest request) {
        return this.rawClient.retrieve(id, request).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>Transaction</code> object with the given <code>id</code>.
     */
    public CompletableFuture<Transaction> retrieve(
            String id, TransactionsRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).thenApply(response -> response.body());
    }
}
