/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.hris.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class GroupsRetrieveRequestRemoteFields {
    public static final GroupsRetrieveRequestRemoteFields TYPE =
            new GroupsRetrieveRequestRemoteFields(Value.TYPE, "type");

    private final Value value;

    private final String string;

    GroupsRetrieveRequestRemoteFields(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof GroupsRetrieveRequestRemoteFields
                        && this.string.equals(((GroupsRetrieveRequestRemoteFields) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TYPE:
                return visitor.visitType();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static GroupsRetrieveRequestRemoteFields valueOf(String value) {
        switch (value) {
            case "type":
                return TYPE;
            default:
                return new GroupsRetrieveRequestRemoteFields(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        TYPE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitType();

        T visitUnknown(String unknownType);
    }
}
