/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.knowledgebase.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class GroupsRetrieveRequestExpandItem {
    public static final GroupsRetrieveRequestExpandItem PARENT_GROUP =
            new GroupsRetrieveRequestExpandItem(Value.PARENT_GROUP, "parent_group");

    public static final GroupsRetrieveRequestExpandItem USERS =
            new GroupsRetrieveRequestExpandItem(Value.USERS, "users");

    private final Value value;

    private final String string;

    GroupsRetrieveRequestExpandItem(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof GroupsRetrieveRequestExpandItem
                        && this.string.equals(((GroupsRetrieveRequestExpandItem) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PARENT_GROUP:
                return visitor.visitParentGroup();
            case USERS:
                return visitor.visitUsers();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static GroupsRetrieveRequestExpandItem valueOf(String value) {
        switch (value) {
            case "parent_group":
                return PARENT_GROUP;
            case "users":
                return USERS;
            default:
                return new GroupsRetrieveRequestExpandItem(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PARENT_GROUP,

        USERS,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitParentGroup();

        T visitUsers();

        T visitUnknown(String unknownType);
    }
}
