/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.resources.ats.eeocs;

import com.merge.api.core.ClientOptions;
import com.merge.api.core.RequestOptions;
import com.merge.api.resources.ats.eeocs.requests.EeocsListRequest;
import com.merge.api.resources.ats.eeocs.requests.EeocsRetrieveRequest;
import com.merge.api.resources.ats.types.Eeoc;
import com.merge.api.resources.ats.types.PaginatedEeocList;
import java.util.concurrent.CompletableFuture;

public class AsyncEeocsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEeocsClient rawClient;

    public AsyncEeocsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEeocsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEeocsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a list of <code>EEOC</code> objects.
     */
    public CompletableFuture<PaginatedEeocList> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Returns a list of <code>EEOC</code> objects.
     */
    public CompletableFuture<PaginatedEeocList> list(EeocsListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Returns a list of <code>EEOC</code> objects.
     */
    public CompletableFuture<PaginatedEeocList> list(EeocsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns an <code>EEOC</code> object with the given <code>id</code>.
     */
    public CompletableFuture<Eeoc> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Returns an <code>EEOC</code> object with the given <code>id</code>.
     */
    public CompletableFuture<Eeoc> retrieve(String id, EeocsRetrieveRequest request) {
        return this.rawClient.retrieve(id, request).thenApply(response -> response.body());
    }

    /**
     * Returns an <code>EEOC</code> object with the given <code>id</code>.
     */
    public CompletableFuture<Eeoc> retrieve(String id, EeocsRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).thenApply(response -> response.body());
    }
}
