/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.resources.crm.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum EnabledActionsEnum {
    READ("READ"),

    WRITE("WRITE");

    private final String value;

    EnabledActionsEnum(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
