/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.resources.crm.tasks.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TasksListRequestExpand {
    public static final TasksListRequestExpand OWNER = new TasksListRequestExpand(Value.OWNER, "owner");

    public static final TasksListRequestExpand OWNER_OPPORTUNITY =
            new TasksListRequestExpand(Value.OWNER_OPPORTUNITY, "owner,opportunity");

    public static final TasksListRequestExpand OPPORTUNITY =
            new TasksListRequestExpand(Value.OPPORTUNITY, "opportunity");

    public static final TasksListRequestExpand OWNER_ACCOUNT =
            new TasksListRequestExpand(Value.OWNER_ACCOUNT, "owner,account");

    public static final TasksListRequestExpand OWNER_ACCOUNT_OPPORTUNITY =
            new TasksListRequestExpand(Value.OWNER_ACCOUNT_OPPORTUNITY, "owner,account,opportunity");

    public static final TasksListRequestExpand ACCOUNT = new TasksListRequestExpand(Value.ACCOUNT, "account");

    public static final TasksListRequestExpand ACCOUNT_OPPORTUNITY =
            new TasksListRequestExpand(Value.ACCOUNT_OPPORTUNITY, "account,opportunity");

    private final Value value;

    private final String string;

    TasksListRequestExpand(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof TasksListRequestExpand
                        && this.string.equals(((TasksListRequestExpand) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OWNER:
                return visitor.visitOwner();
            case OWNER_OPPORTUNITY:
                return visitor.visitOwnerOpportunity();
            case OPPORTUNITY:
                return visitor.visitOpportunity();
            case OWNER_ACCOUNT:
                return visitor.visitOwnerAccount();
            case OWNER_ACCOUNT_OPPORTUNITY:
                return visitor.visitOwnerAccountOpportunity();
            case ACCOUNT:
                return visitor.visitAccount();
            case ACCOUNT_OPPORTUNITY:
                return visitor.visitAccountOpportunity();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TasksListRequestExpand valueOf(String value) {
        switch (value) {
            case "owner":
                return OWNER;
            case "owner,opportunity":
                return OWNER_OPPORTUNITY;
            case "opportunity":
                return OPPORTUNITY;
            case "owner,account":
                return OWNER_ACCOUNT;
            case "owner,account,opportunity":
                return OWNER_ACCOUNT_OPPORTUNITY;
            case "account":
                return ACCOUNT;
            case "account,opportunity":
                return ACCOUNT_OPPORTUNITY;
            default:
                return new TasksListRequestExpand(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ACCOUNT,

        ACCOUNT_OPPORTUNITY,

        OPPORTUNITY,

        OWNER,

        OWNER_ACCOUNT,

        OWNER_ACCOUNT_OPPORTUNITY,

        OWNER_OPPORTUNITY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAccount();

        T visitAccountOpportunity();

        T visitOpportunity();

        T visitOwner();

        T visitOwnerAccount();

        T visitOwnerAccountOpportunity();

        T visitOwnerOpportunity();

        T visitUnknown(String unknownType);
    }
}
