/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.ats;

import com.merge.api.ats.types.JobPosting;
import com.merge.api.ats.types.JobPostingsListRequest;
import com.merge.api.ats.types.JobPostingsRetrieveRequest;
import com.merge.api.ats.types.PaginatedJobPostingList;
import com.merge.api.core.ClientOptions;
import com.merge.api.core.RequestOptions;
import java.util.concurrent.CompletableFuture;

public class AsyncJobPostingsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawJobPostingsClient rawClient;

    public AsyncJobPostingsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawJobPostingsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawJobPostingsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a list of <code>JobPosting</code> objects.
     */
    public CompletableFuture<PaginatedJobPostingList> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Returns a list of <code>JobPosting</code> objects.
     */
    public CompletableFuture<PaginatedJobPostingList> list(JobPostingsListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Returns a list of <code>JobPosting</code> objects.
     */
    public CompletableFuture<PaginatedJobPostingList> list(
            JobPostingsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>JobPosting</code> object with the given <code>id</code>.
     */
    public CompletableFuture<JobPosting> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>JobPosting</code> object with the given <code>id</code>.
     */
    public CompletableFuture<JobPosting> retrieve(String id, JobPostingsRetrieveRequest request) {
        return this.rawClient.retrieve(id, request).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>JobPosting</code> object with the given <code>id</code>.
     */
    public CompletableFuture<JobPosting> retrieve(
            String id, JobPostingsRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).thenApply(response -> response.body());
    }
}
