/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.ats;

import com.merge.api.ats.types.InterviewsListRequest;
import com.merge.api.ats.types.InterviewsRetrieveRequest;
import com.merge.api.ats.types.MetaResponse;
import com.merge.api.ats.types.PaginatedScheduledInterviewList;
import com.merge.api.ats.types.ScheduledInterview;
import com.merge.api.ats.types.ScheduledInterviewEndpointRequest;
import com.merge.api.ats.types.ScheduledInterviewResponse;
import com.merge.api.core.ApiError;
import com.merge.api.core.ClientOptions;
import com.merge.api.core.MediaTypes;
import com.merge.api.core.MergeApiHttpResponse;
import com.merge.api.core.MergeException;
import com.merge.api.core.ObjectMappers;
import com.merge.api.core.QueryStringMapper;
import com.merge.api.core.RequestOptions;
import com.merge.api.core.SyncPagingIterable;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawInterviewsClient {
    protected final ClientOptions clientOptions;

    public RawInterviewsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns a list of <code>ScheduledInterview</code> objects.
     */
    public MergeApiHttpResponse<SyncPagingIterable<ScheduledInterview>> list() {
        return list(InterviewsListRequest.builder().build());
    }

    /**
     * Returns a list of <code>ScheduledInterview</code> objects.
     */
    public MergeApiHttpResponse<SyncPagingIterable<ScheduledInterview>> list(InterviewsListRequest request) {
        return list(request, null);
    }

    /**
     * Returns a list of <code>ScheduledInterview</code> objects.
     */
    public MergeApiHttpResponse<SyncPagingIterable<ScheduledInterview>> list(
            InterviewsListRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("ats/v1/interviews");
        if (request.getApplicationId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "application_id", request.getApplicationId().get(), false);
        }
        if (request.getCreatedAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "created_after", request.getCreatedAfter().get(), false);
        }
        if (request.getCreatedBefore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "created_before", request.getCreatedBefore().get(), false);
        }
        if (request.getCursor().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "cursor", request.getCursor().get(), false);
        }
        if (request.getIncludeDeletedData().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "include_deleted_data",
                    request.getIncludeDeletedData().get(),
                    false);
        }
        if (request.getIncludeRemoteData().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "include_remote_data",
                    request.getIncludeRemoteData().get(),
                    false);
        }
        if (request.getIncludeShellData().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "include_shell_data", request.getIncludeShellData().get(), false);
        }
        if (request.getJobId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "job_id", request.getJobId().get(), false);
        }
        if (request.getJobInterviewStageId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "job_interview_stage_id",
                    request.getJobInterviewStageId().get(),
                    false);
        }
        if (request.getModifiedAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "modified_after", request.getModifiedAfter().get(), false);
        }
        if (request.getModifiedBefore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "modified_before", request.getModifiedBefore().get(), false);
        }
        if (request.getOrganizerId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "organizer_id", request.getOrganizerId().get(), false);
        }
        if (request.getPageSize().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page_size", request.getPageSize().get(), false);
        }
        if (request.getRemoteFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "remote_fields", request.getRemoteFields().get(), false);
        }
        if (request.getRemoteId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "remote_id", request.getRemoteId().get(), false);
        }
        if (request.getShowEnumOrigins().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "show_enum_origins", request.getShowEnumOrigins().get(), false);
        }
        if (request.getExpand().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "expand", request.getExpand().get(), true);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                PaginatedScheduledInterviewList parsedResponse =
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedScheduledInterviewList.class);
                Optional<String> startingAfter = parsedResponse.getNext();
                InterviewsListRequest nextRequest = InterviewsListRequest.builder()
                        .from(request)
                        .cursor(startingAfter)
                        .build();
                List<ScheduledInterview> result = parsedResponse.getResults().orElse(Collections.emptyList());
                return new MergeApiHttpResponse<>(
                        new SyncPagingIterable<ScheduledInterview>(
                                startingAfter.isPresent(), result, parsedResponse, () -> list(
                                                nextRequest, requestOptions)
                                        .body()),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApiError("Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MergeException("Network error executing HTTP request", e);
        }
    }

    /**
     * Creates a <code>ScheduledInterview</code> object with the given values.
     */
    public MergeApiHttpResponse<ScheduledInterviewResponse> create(ScheduledInterviewEndpointRequest request) {
        return create(request, null);
    }

    /**
     * Creates a <code>ScheduledInterview</code> object with the given values.
     */
    public MergeApiHttpResponse<ScheduledInterviewResponse> create(
            ScheduledInterviewEndpointRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("ats/v1/interviews");
        if (request.getIsDebugMode().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "is_debug_mode", request.getIsDebugMode().get(), false);
        }
        if (request.getRunAsync().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "run_async", request.getRunAsync().get(), false);
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MergeApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ScheduledInterviewResponse.class),
                        response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApiError("Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MergeException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns a <code>ScheduledInterview</code> object with the given <code>id</code>.
     */
    public MergeApiHttpResponse<ScheduledInterview> retrieve(String id) {
        return retrieve(id, InterviewsRetrieveRequest.builder().build());
    }

    /**
     * Returns a <code>ScheduledInterview</code> object with the given <code>id</code>.
     */
    public MergeApiHttpResponse<ScheduledInterview> retrieve(String id, InterviewsRetrieveRequest request) {
        return retrieve(id, request, null);
    }

    /**
     * Returns a <code>ScheduledInterview</code> object with the given <code>id</code>.
     */
    public MergeApiHttpResponse<ScheduledInterview> retrieve(
            String id, InterviewsRetrieveRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("ats/v1/interviews")
                .addPathSegment(id);
        if (request.getIncludeRemoteData().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "include_remote_data",
                    request.getIncludeRemoteData().get(),
                    false);
        }
        if (request.getIncludeShellData().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "include_shell_data", request.getIncludeShellData().get(), false);
        }
        if (request.getRemoteFields().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "remote_fields", request.getRemoteFields().get(), false);
        }
        if (request.getShowEnumOrigins().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "show_enum_origins", request.getShowEnumOrigins().get(), false);
        }
        if (request.getExpand().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "expand", request.getExpand().get(), true);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MergeApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ScheduledInterview.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApiError("Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MergeException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns metadata for <code>ScheduledInterview</code> POSTs.
     */
    public MergeApiHttpResponse<MetaResponse> metaPostRetrieve() {
        return metaPostRetrieve(null);
    }

    /**
     * Returns metadata for <code>ScheduledInterview</code> POSTs.
     */
    public MergeApiHttpResponse<MetaResponse> metaPostRetrieve(RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("ats/v1/interviews/meta/post")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MergeApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MetaResponse.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApiError("Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MergeException("Network error executing HTTP request", e);
        }
    }
}
