/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.ats;

import com.merge.api.ats.types.PaginatedTagList;
import com.merge.api.ats.types.TagsListRequest;
import com.merge.api.core.ClientOptions;
import com.merge.api.core.RequestOptions;

public class TagsClient {
    protected final ClientOptions clientOptions;

    private final RawTagsClient rawClient;

    public TagsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawTagsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawTagsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a list of <code>Tag</code> objects.
     */
    public PaginatedTagList list() {
        return this.rawClient.list().body();
    }

    /**
     * Returns a list of <code>Tag</code> objects.
     */
    public PaginatedTagList list(TagsListRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Returns a list of <code>Tag</code> objects.
     */
    public PaginatedTagList list(TagsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }
}
