package dev.merge.api.models.crm

import dev.merge.api.models.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CustomObjectClassAssociationTypeCreateParamsTest {

    @Test
    fun createCustomObjectClassAssociationTypeCreateParams() {
        CustomObjectClassAssociationTypeCreateParams.builder()
            .customObjectClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
            .model(
                CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest.builder()
                    .sourceObjectClass(
                        CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest
                            .ObjectClassDescriptionRequest
                            .builder()
                            .id("x")
                            .originType(
                                CustomObjectClassAssociationTypeCreateParams
                                    .AssociationTypeRequestRequest
                                    .ObjectClassDescriptionRequest
                                    .OriginTypeEnum
                                    .CUSTOM_OBJECT
                            )
                            .build()
                    )
                    .targetObjectClasses(
                        listOf(
                            CustomObjectClassAssociationTypeCreateParams
                                .AssociationTypeRequestRequest
                                .ObjectClassDescriptionRequest
                                .builder()
                                .id("x")
                                .originType(
                                    CustomObjectClassAssociationTypeCreateParams
                                        .AssociationTypeRequestRequest
                                        .ObjectClassDescriptionRequest
                                        .OriginTypeEnum
                                        .CUSTOM_OBJECT
                                )
                                .build()
                        )
                    )
                    .remoteKeyName("x")
                    .displayName("x")
                    .cardinality(
                        CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest
                            .CardinalityEnum
                            .ONE_TO_ONE
                    )
                    .isRequired(true)
                    .build()
            )
            .isDebugMode(true)
            .runAsync(true)
            .build()
    }

    @Test
    fun getQueryParams() {
        val params =
            CustomObjectClassAssociationTypeCreateParams.builder()
                .customObjectClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .model(
                    CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest
                        .builder()
                        .sourceObjectClass(
                            CustomObjectClassAssociationTypeCreateParams
                                .AssociationTypeRequestRequest
                                .ObjectClassDescriptionRequest
                                .builder()
                                .id("x")
                                .originType(
                                    CustomObjectClassAssociationTypeCreateParams
                                        .AssociationTypeRequestRequest
                                        .ObjectClassDescriptionRequest
                                        .OriginTypeEnum
                                        .CUSTOM_OBJECT
                                )
                                .build()
                        )
                        .targetObjectClasses(
                            listOf(
                                CustomObjectClassAssociationTypeCreateParams
                                    .AssociationTypeRequestRequest
                                    .ObjectClassDescriptionRequest
                                    .builder()
                                    .id("x")
                                    .originType(
                                        CustomObjectClassAssociationTypeCreateParams
                                            .AssociationTypeRequestRequest
                                            .ObjectClassDescriptionRequest
                                            .OriginTypeEnum
                                            .CUSTOM_OBJECT
                                    )
                                    .build()
                            )
                        )
                        .remoteKeyName("x")
                        .displayName("x")
                        .cardinality(
                            CustomObjectClassAssociationTypeCreateParams
                                .AssociationTypeRequestRequest
                                .CardinalityEnum
                                .ONE_TO_ONE
                        )
                        .isRequired(true)
                        .build()
                )
                .isDebugMode(true)
                .runAsync(true)
                .build()
        val expected = mutableMapOf<String, List<String>>()
        expected.put("is_debug_mode", listOf("true"))
        expected.put("run_async", listOf("true"))
        assertThat(params.getQueryParams()).isEqualTo(expected)
    }

    @Test
    fun getQueryParamsWithoutOptionalFields() {
        val params =
            CustomObjectClassAssociationTypeCreateParams.builder()
                .customObjectClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .model(
                    CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest
                        .builder()
                        .sourceObjectClass(
                            CustomObjectClassAssociationTypeCreateParams
                                .AssociationTypeRequestRequest
                                .ObjectClassDescriptionRequest
                                .builder()
                                .id("x")
                                .originType(
                                    CustomObjectClassAssociationTypeCreateParams
                                        .AssociationTypeRequestRequest
                                        .ObjectClassDescriptionRequest
                                        .OriginTypeEnum
                                        .CUSTOM_OBJECT
                                )
                                .build()
                        )
                        .targetObjectClasses(
                            listOf(
                                CustomObjectClassAssociationTypeCreateParams
                                    .AssociationTypeRequestRequest
                                    .ObjectClassDescriptionRequest
                                    .builder()
                                    .id("x")
                                    .originType(
                                        CustomObjectClassAssociationTypeCreateParams
                                            .AssociationTypeRequestRequest
                                            .ObjectClassDescriptionRequest
                                            .OriginTypeEnum
                                            .CUSTOM_OBJECT
                                    )
                                    .build()
                            )
                        )
                        .remoteKeyName("x")
                        .build()
                )
                .build()
        val expected = mutableMapOf<String, List<String>>()
        assertThat(params.getQueryParams()).isEqualTo(expected)
    }

    @Test
    fun getBody() {
        val params =
            CustomObjectClassAssociationTypeCreateParams.builder()
                .customObjectClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .model(
                    CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest
                        .builder()
                        .sourceObjectClass(
                            CustomObjectClassAssociationTypeCreateParams
                                .AssociationTypeRequestRequest
                                .ObjectClassDescriptionRequest
                                .builder()
                                .id("x")
                                .originType(
                                    CustomObjectClassAssociationTypeCreateParams
                                        .AssociationTypeRequestRequest
                                        .ObjectClassDescriptionRequest
                                        .OriginTypeEnum
                                        .CUSTOM_OBJECT
                                )
                                .build()
                        )
                        .targetObjectClasses(
                            listOf(
                                CustomObjectClassAssociationTypeCreateParams
                                    .AssociationTypeRequestRequest
                                    .ObjectClassDescriptionRequest
                                    .builder()
                                    .id("x")
                                    .originType(
                                        CustomObjectClassAssociationTypeCreateParams
                                            .AssociationTypeRequestRequest
                                            .ObjectClassDescriptionRequest
                                            .OriginTypeEnum
                                            .CUSTOM_OBJECT
                                    )
                                    .build()
                            )
                        )
                        .remoteKeyName("x")
                        .displayName("x")
                        .cardinality(
                            CustomObjectClassAssociationTypeCreateParams
                                .AssociationTypeRequestRequest
                                .CardinalityEnum
                                .ONE_TO_ONE
                        )
                        .isRequired(true)
                        .build()
                )
                .isDebugMode(true)
                .runAsync(true)
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.model())
            .isEqualTo(
                CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest.builder()
                    .sourceObjectClass(
                        CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest
                            .ObjectClassDescriptionRequest
                            .builder()
                            .id("x")
                            .originType(
                                CustomObjectClassAssociationTypeCreateParams
                                    .AssociationTypeRequestRequest
                                    .ObjectClassDescriptionRequest
                                    .OriginTypeEnum
                                    .CUSTOM_OBJECT
                            )
                            .build()
                    )
                    .targetObjectClasses(
                        listOf(
                            CustomObjectClassAssociationTypeCreateParams
                                .AssociationTypeRequestRequest
                                .ObjectClassDescriptionRequest
                                .builder()
                                .id("x")
                                .originType(
                                    CustomObjectClassAssociationTypeCreateParams
                                        .AssociationTypeRequestRequest
                                        .ObjectClassDescriptionRequest
                                        .OriginTypeEnum
                                        .CUSTOM_OBJECT
                                )
                                .build()
                        )
                    )
                    .remoteKeyName("x")
                    .displayName("x")
                    .cardinality(
                        CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest
                            .CardinalityEnum
                            .ONE_TO_ONE
                    )
                    .isRequired(true)
                    .build()
            )
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            CustomObjectClassAssociationTypeCreateParams.builder()
                .customObjectClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .model(
                    CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest
                        .builder()
                        .sourceObjectClass(
                            CustomObjectClassAssociationTypeCreateParams
                                .AssociationTypeRequestRequest
                                .ObjectClassDescriptionRequest
                                .builder()
                                .id("x")
                                .originType(
                                    CustomObjectClassAssociationTypeCreateParams
                                        .AssociationTypeRequestRequest
                                        .ObjectClassDescriptionRequest
                                        .OriginTypeEnum
                                        .CUSTOM_OBJECT
                                )
                                .build()
                        )
                        .targetObjectClasses(
                            listOf(
                                CustomObjectClassAssociationTypeCreateParams
                                    .AssociationTypeRequestRequest
                                    .ObjectClassDescriptionRequest
                                    .builder()
                                    .id("x")
                                    .originType(
                                        CustomObjectClassAssociationTypeCreateParams
                                            .AssociationTypeRequestRequest
                                            .ObjectClassDescriptionRequest
                                            .OriginTypeEnum
                                            .CUSTOM_OBJECT
                                    )
                                    .build()
                            )
                        )
                        .remoteKeyName("x")
                        .build()
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.model())
            .isEqualTo(
                CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest.builder()
                    .sourceObjectClass(
                        CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest
                            .ObjectClassDescriptionRequest
                            .builder()
                            .id("x")
                            .originType(
                                CustomObjectClassAssociationTypeCreateParams
                                    .AssociationTypeRequestRequest
                                    .ObjectClassDescriptionRequest
                                    .OriginTypeEnum
                                    .CUSTOM_OBJECT
                            )
                            .build()
                    )
                    .targetObjectClasses(
                        listOf(
                            CustomObjectClassAssociationTypeCreateParams
                                .AssociationTypeRequestRequest
                                .ObjectClassDescriptionRequest
                                .builder()
                                .id("x")
                                .originType(
                                    CustomObjectClassAssociationTypeCreateParams
                                        .AssociationTypeRequestRequest
                                        .ObjectClassDescriptionRequest
                                        .OriginTypeEnum
                                        .CUSTOM_OBJECT
                                )
                                .build()
                        )
                    )
                    .remoteKeyName("x")
                    .build()
            )
    }

    @Test
    fun getPathParam() {
        val params =
            CustomObjectClassAssociationTypeCreateParams.builder()
                .customObjectClassId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .model(
                    CustomObjectClassAssociationTypeCreateParams.AssociationTypeRequestRequest
                        .builder()
                        .sourceObjectClass(
                            CustomObjectClassAssociationTypeCreateParams
                                .AssociationTypeRequestRequest
                                .ObjectClassDescriptionRequest
                                .builder()
                                .id("x")
                                .originType(
                                    CustomObjectClassAssociationTypeCreateParams
                                        .AssociationTypeRequestRequest
                                        .ObjectClassDescriptionRequest
                                        .OriginTypeEnum
                                        .CUSTOM_OBJECT
                                )
                                .build()
                        )
                        .targetObjectClasses(
                            listOf(
                                CustomObjectClassAssociationTypeCreateParams
                                    .AssociationTypeRequestRequest
                                    .ObjectClassDescriptionRequest
                                    .builder()
                                    .id("x")
                                    .originType(
                                        CustomObjectClassAssociationTypeCreateParams
                                            .AssociationTypeRequestRequest
                                            .ObjectClassDescriptionRequest
                                            .OriginTypeEnum
                                            .CUSTOM_OBJECT
                                    )
                                    .build()
                            )
                        )
                        .remoteKeyName("x")
                        .build()
                )
                .build()
        assertThat(params).isNotNull
        // path param "customObjectClassId"
        assertThat(params.getPathParam(0)).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        // out-of-bound path param
        assertThat(params.getPathParam(1)).isEqualTo("")
    }
}
