package dev.merge.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CommonModelScopeTest {

    @Test
    fun createCommonModelScope() {
        val commonModelScope =
            CommonModelScope.builder()
                .organizationLevelScopes(
                    CommonModelScope.CommonModelScopeData.builder()
                        .commonModels(
                            listOf(
                                CommonModelScope.CommonModelScopeData
                                    .CommonModelScopesDisabledModels
                                    .builder()
                                    .modelName("string")
                                    .modelId("string")
                                    .enabledActions(
                                        listOf(
                                            CommonModelScope.CommonModelScopeData
                                                .CommonModelScopesDisabledModels
                                                .CommonModelScopesDisabledModelsEnabledActionsEnum
                                                .ENABLED_ACTION_READ
                                        )
                                    )
                                    .isDisabled(true)
                                    .disabledFields(listOf("string"))
                                    .build()
                            )
                        )
                        .linkedAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .scopeOverrides(
                    listOf(
                        CommonModelScope.CommonModelScopeData.builder()
                            .commonModels(
                                listOf(
                                    CommonModelScope.CommonModelScopeData
                                        .CommonModelScopesDisabledModels
                                        .builder()
                                        .modelName("string")
                                        .modelId("string")
                                        .enabledActions(
                                            listOf(
                                                CommonModelScope.CommonModelScopeData
                                                    .CommonModelScopesDisabledModels
                                                    .CommonModelScopesDisabledModelsEnabledActionsEnum
                                                    .ENABLED_ACTION_READ
                                            )
                                        )
                                        .isDisabled(true)
                                        .disabledFields(listOf("string"))
                                        .build()
                                )
                            )
                            .linkedAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                )
                .build()
        assertThat(commonModelScope).isNotNull
        assertThat(commonModelScope.organizationLevelScopes())
            .contains(
                CommonModelScope.CommonModelScopeData.builder()
                    .commonModels(
                        listOf(
                            CommonModelScope.CommonModelScopeData.CommonModelScopesDisabledModels
                                .builder()
                                .modelName("string")
                                .modelId("string")
                                .enabledActions(
                                    listOf(
                                        CommonModelScope.CommonModelScopeData
                                            .CommonModelScopesDisabledModels
                                            .CommonModelScopesDisabledModelsEnabledActionsEnum
                                            .ENABLED_ACTION_READ
                                    )
                                )
                                .isDisabled(true)
                                .disabledFields(listOf("string"))
                                .build()
                        )
                    )
                    .linkedAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
        assertThat(commonModelScope.scopeOverrides())
            .containsExactly(
                CommonModelScope.CommonModelScopeData.builder()
                    .commonModels(
                        listOf(
                            CommonModelScope.CommonModelScopeData.CommonModelScopesDisabledModels
                                .builder()
                                .modelName("string")
                                .modelId("string")
                                .enabledActions(
                                    listOf(
                                        CommonModelScope.CommonModelScopeData
                                            .CommonModelScopesDisabledModels
                                            .CommonModelScopesDisabledModelsEnabledActionsEnum
                                            .ENABLED_ACTION_READ
                                    )
                                )
                                .isDisabled(true)
                                .disabledFields(listOf("string"))
                                .build()
                        )
                    )
                    .linkedAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
    }
}
