/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.accounting.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.merge.api.core.Nullable;
import com.merge.api.core.NullableNonemptyFilter;
import com.merge.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BankFeedTransaction.Builder.class)
public final class BankFeedTransaction {
    private final Optional<String> id;

    private final Optional<String> remoteId;

    private final Optional<OffsetDateTime> createdAt;

    private final Optional<OffsetDateTime> modifiedAt;

    private final Optional<BankFeedTransactionBankFeedAccount> bankFeedAccount;

    private final Optional<OffsetDateTime> transactionDate;

    private final Optional<OffsetDateTime> postedDate;

    private final Optional<Double> amount;

    private final Optional<String> description;

    private final Optional<String> transactionType;

    private final Optional<String> payee;

    private final Optional<BankFeedTransactionCreditOrDebit> creditOrDebit;

    private final Optional<String> sourceTransactionId;

    private final Optional<Boolean> remoteWasDeleted;

    private final Optional<Boolean> isProcessed;

    private final Map<String, Object> additionalProperties;

    private BankFeedTransaction(
            Optional<String> id,
            Optional<String> remoteId,
            Optional<OffsetDateTime> createdAt,
            Optional<OffsetDateTime> modifiedAt,
            Optional<BankFeedTransactionBankFeedAccount> bankFeedAccount,
            Optional<OffsetDateTime> transactionDate,
            Optional<OffsetDateTime> postedDate,
            Optional<Double> amount,
            Optional<String> description,
            Optional<String> transactionType,
            Optional<String> payee,
            Optional<BankFeedTransactionCreditOrDebit> creditOrDebit,
            Optional<String> sourceTransactionId,
            Optional<Boolean> remoteWasDeleted,
            Optional<Boolean> isProcessed,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.remoteId = remoteId;
        this.createdAt = createdAt;
        this.modifiedAt = modifiedAt;
        this.bankFeedAccount = bankFeedAccount;
        this.transactionDate = transactionDate;
        this.postedDate = postedDate;
        this.amount = amount;
        this.description = description;
        this.transactionType = transactionType;
        this.payee = payee;
        this.creditOrDebit = creditOrDebit;
        this.sourceTransactionId = sourceTransactionId;
        this.remoteWasDeleted = remoteWasDeleted;
        this.isProcessed = isProcessed;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return The third-party API ID of the matching object.
     */
    @JsonIgnore
    public Optional<String> getRemoteId() {
        if (remoteId == null) {
            return Optional.empty();
        }
        return remoteId;
    }

    /**
     * @return The datetime that this object was created by Merge.
     */
    @JsonProperty("created_at")
    public Optional<OffsetDateTime> getCreatedAt() {
        return createdAt;
    }

    /**
     * @return The datetime that this object was modified by Merge.
     */
    @JsonProperty("modified_at")
    public Optional<OffsetDateTime> getModifiedAt() {
        return modifiedAt;
    }

    /**
     * @return The bank feed account associated with the transaction.
     */
    @JsonIgnore
    public Optional<BankFeedTransactionBankFeedAccount> getBankFeedAccount() {
        if (bankFeedAccount == null) {
            return Optional.empty();
        }
        return bankFeedAccount;
    }

    /**
     * @return The date that the transaction occurred.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getTransactionDate() {
        if (transactionDate == null) {
            return Optional.empty();
        }
        return transactionDate;
    }

    /**
     * @return The date the transaction was posted to the bank account.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getPostedDate() {
        if (postedDate == null) {
            return Optional.empty();
        }
        return postedDate;
    }

    /**
     * @return The amount of the transaction.
     */
    @JsonIgnore
    public Optional<Double> getAmount() {
        if (amount == null) {
            return Optional.empty();
        }
        return amount;
    }

    /**
     * @return The description of the transaction.
     */
    @JsonIgnore
    public Optional<String> getDescription() {
        if (description == null) {
            return Optional.empty();
        }
        return description;
    }

    /**
     * @return The underlying type of the transaction.
     */
    @JsonIgnore
    public Optional<String> getTransactionType() {
        if (transactionType == null) {
            return Optional.empty();
        }
        return transactionType;
    }

    /**
     * @return The person or merchant who initiated the transaction, or alternatively, to whom the transaction was paid.
     */
    @JsonIgnore
    public Optional<String> getPayee() {
        if (payee == null) {
            return Optional.empty();
        }
        return payee;
    }

    /**
     * @return If the transaction is of type debit or credit.
     * <ul>
     * <li><code>CREDIT</code> - CREDIT</li>
     * <li><code>DEBIT</code> - DEBIT</li>
     * </ul>
     */
    @JsonIgnore
    public Optional<BankFeedTransactionCreditOrDebit> getCreditOrDebit() {
        if (creditOrDebit == null) {
            return Optional.empty();
        }
        return creditOrDebit;
    }

    /**
     * @return The customer’s identifier for the transaction.
     */
    @JsonIgnore
    public Optional<String> getSourceTransactionId() {
        if (sourceTransactionId == null) {
            return Optional.empty();
        }
        return sourceTransactionId;
    }

    /**
     * @return Indicates whether or not this object has been deleted in the third party platform. Full coverage deletion detection is a premium add-on. Native deletion detection is offered for free with limited coverage. <a href="https://docs.merge.dev/integrations/hris/supported-features/">Learn more</a>.
     */
    @JsonProperty("remote_was_deleted")
    public Optional<Boolean> getRemoteWasDeleted() {
        return remoteWasDeleted;
    }

    /**
     * @return Whether or not this transaction has been processed by the external system. For example, NetSuite writes this field as True when the SuiteApp has processed the transaction.
     */
    @JsonProperty("is_processed")
    public Optional<Boolean> getIsProcessed() {
        return isProcessed;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("remote_id")
    private Optional<String> _getRemoteId() {
        return remoteId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("bank_feed_account")
    private Optional<BankFeedTransactionBankFeedAccount> _getBankFeedAccount() {
        return bankFeedAccount;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("transaction_date")
    private Optional<OffsetDateTime> _getTransactionDate() {
        return transactionDate;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("posted_date")
    private Optional<OffsetDateTime> _getPostedDate() {
        return postedDate;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("amount")
    private Optional<Double> _getAmount() {
        return amount;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("description")
    private Optional<String> _getDescription() {
        return description;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("transaction_type")
    private Optional<String> _getTransactionType() {
        return transactionType;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("payee")
    private Optional<String> _getPayee() {
        return payee;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("credit_or_debit")
    private Optional<BankFeedTransactionCreditOrDebit> _getCreditOrDebit() {
        return creditOrDebit;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("source_transaction_id")
    private Optional<String> _getSourceTransactionId() {
        return sourceTransactionId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BankFeedTransaction && equalTo((BankFeedTransaction) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BankFeedTransaction other) {
        return id.equals(other.id)
                && remoteId.equals(other.remoteId)
                && createdAt.equals(other.createdAt)
                && modifiedAt.equals(other.modifiedAt)
                && bankFeedAccount.equals(other.bankFeedAccount)
                && transactionDate.equals(other.transactionDate)
                && postedDate.equals(other.postedDate)
                && amount.equals(other.amount)
                && description.equals(other.description)
                && transactionType.equals(other.transactionType)
                && payee.equals(other.payee)
                && creditOrDebit.equals(other.creditOrDebit)
                && sourceTransactionId.equals(other.sourceTransactionId)
                && remoteWasDeleted.equals(other.remoteWasDeleted)
                && isProcessed.equals(other.isProcessed);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.remoteId,
                this.createdAt,
                this.modifiedAt,
                this.bankFeedAccount,
                this.transactionDate,
                this.postedDate,
                this.amount,
                this.description,
                this.transactionType,
                this.payee,
                this.creditOrDebit,
                this.sourceTransactionId,
                this.remoteWasDeleted,
                this.isProcessed);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<String> remoteId = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        private Optional<OffsetDateTime> modifiedAt = Optional.empty();

        private Optional<BankFeedTransactionBankFeedAccount> bankFeedAccount = Optional.empty();

        private Optional<OffsetDateTime> transactionDate = Optional.empty();

        private Optional<OffsetDateTime> postedDate = Optional.empty();

        private Optional<Double> amount = Optional.empty();

        private Optional<String> description = Optional.empty();

        private Optional<String> transactionType = Optional.empty();

        private Optional<String> payee = Optional.empty();

        private Optional<BankFeedTransactionCreditOrDebit> creditOrDebit = Optional.empty();

        private Optional<String> sourceTransactionId = Optional.empty();

        private Optional<Boolean> remoteWasDeleted = Optional.empty();

        private Optional<Boolean> isProcessed = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BankFeedTransaction other) {
            id(other.getId());
            remoteId(other.getRemoteId());
            createdAt(other.getCreatedAt());
            modifiedAt(other.getModifiedAt());
            bankFeedAccount(other.getBankFeedAccount());
            transactionDate(other.getTransactionDate());
            postedDate(other.getPostedDate());
            amount(other.getAmount());
            description(other.getDescription());
            transactionType(other.getTransactionType());
            payee(other.getPayee());
            creditOrDebit(other.getCreditOrDebit());
            sourceTransactionId(other.getSourceTransactionId());
            remoteWasDeleted(other.getRemoteWasDeleted());
            isProcessed(other.getIsProcessed());
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>The third-party API ID of the matching object.</p>
         */
        @JsonSetter(value = "remote_id", nulls = Nulls.SKIP)
        public Builder remoteId(Optional<String> remoteId) {
            this.remoteId = remoteId;
            return this;
        }

        public Builder remoteId(String remoteId) {
            this.remoteId = Optional.ofNullable(remoteId);
            return this;
        }

        public Builder remoteId(Nullable<String> remoteId) {
            if (remoteId.isNull()) {
                this.remoteId = null;
            } else if (remoteId.isEmpty()) {
                this.remoteId = Optional.empty();
            } else {
                this.remoteId = Optional.of(remoteId.get());
            }
            return this;
        }

        /**
         * <p>The datetime that this object was created by Merge.</p>
         */
        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public Builder createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * <p>The datetime that this object was modified by Merge.</p>
         */
        @JsonSetter(value = "modified_at", nulls = Nulls.SKIP)
        public Builder modifiedAt(Optional<OffsetDateTime> modifiedAt) {
            this.modifiedAt = modifiedAt;
            return this;
        }

        public Builder modifiedAt(OffsetDateTime modifiedAt) {
            this.modifiedAt = Optional.ofNullable(modifiedAt);
            return this;
        }

        /**
         * <p>The bank feed account associated with the transaction.</p>
         */
        @JsonSetter(value = "bank_feed_account", nulls = Nulls.SKIP)
        public Builder bankFeedAccount(Optional<BankFeedTransactionBankFeedAccount> bankFeedAccount) {
            this.bankFeedAccount = bankFeedAccount;
            return this;
        }

        public Builder bankFeedAccount(BankFeedTransactionBankFeedAccount bankFeedAccount) {
            this.bankFeedAccount = Optional.ofNullable(bankFeedAccount);
            return this;
        }

        public Builder bankFeedAccount(Nullable<BankFeedTransactionBankFeedAccount> bankFeedAccount) {
            if (bankFeedAccount.isNull()) {
                this.bankFeedAccount = null;
            } else if (bankFeedAccount.isEmpty()) {
                this.bankFeedAccount = Optional.empty();
            } else {
                this.bankFeedAccount = Optional.of(bankFeedAccount.get());
            }
            return this;
        }

        /**
         * <p>The date that the transaction occurred.</p>
         */
        @JsonSetter(value = "transaction_date", nulls = Nulls.SKIP)
        public Builder transactionDate(Optional<OffsetDateTime> transactionDate) {
            this.transactionDate = transactionDate;
            return this;
        }

        public Builder transactionDate(OffsetDateTime transactionDate) {
            this.transactionDate = Optional.ofNullable(transactionDate);
            return this;
        }

        public Builder transactionDate(Nullable<OffsetDateTime> transactionDate) {
            if (transactionDate.isNull()) {
                this.transactionDate = null;
            } else if (transactionDate.isEmpty()) {
                this.transactionDate = Optional.empty();
            } else {
                this.transactionDate = Optional.of(transactionDate.get());
            }
            return this;
        }

        /**
         * <p>The date the transaction was posted to the bank account.</p>
         */
        @JsonSetter(value = "posted_date", nulls = Nulls.SKIP)
        public Builder postedDate(Optional<OffsetDateTime> postedDate) {
            this.postedDate = postedDate;
            return this;
        }

        public Builder postedDate(OffsetDateTime postedDate) {
            this.postedDate = Optional.ofNullable(postedDate);
            return this;
        }

        public Builder postedDate(Nullable<OffsetDateTime> postedDate) {
            if (postedDate.isNull()) {
                this.postedDate = null;
            } else if (postedDate.isEmpty()) {
                this.postedDate = Optional.empty();
            } else {
                this.postedDate = Optional.of(postedDate.get());
            }
            return this;
        }

        /**
         * <p>The amount of the transaction.</p>
         */
        @JsonSetter(value = "amount", nulls = Nulls.SKIP)
        public Builder amount(Optional<Double> amount) {
            this.amount = amount;
            return this;
        }

        public Builder amount(Double amount) {
            this.amount = Optional.ofNullable(amount);
            return this;
        }

        public Builder amount(Nullable<Double> amount) {
            if (amount.isNull()) {
                this.amount = null;
            } else if (amount.isEmpty()) {
                this.amount = Optional.empty();
            } else {
                this.amount = Optional.of(amount.get());
            }
            return this;
        }

        /**
         * <p>The description of the transaction.</p>
         */
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public Builder description(Optional<String> description) {
            this.description = description;
            return this;
        }

        public Builder description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        public Builder description(Nullable<String> description) {
            if (description.isNull()) {
                this.description = null;
            } else if (description.isEmpty()) {
                this.description = Optional.empty();
            } else {
                this.description = Optional.of(description.get());
            }
            return this;
        }

        /**
         * <p>The underlying type of the transaction.</p>
         */
        @JsonSetter(value = "transaction_type", nulls = Nulls.SKIP)
        public Builder transactionType(Optional<String> transactionType) {
            this.transactionType = transactionType;
            return this;
        }

        public Builder transactionType(String transactionType) {
            this.transactionType = Optional.ofNullable(transactionType);
            return this;
        }

        public Builder transactionType(Nullable<String> transactionType) {
            if (transactionType.isNull()) {
                this.transactionType = null;
            } else if (transactionType.isEmpty()) {
                this.transactionType = Optional.empty();
            } else {
                this.transactionType = Optional.of(transactionType.get());
            }
            return this;
        }

        /**
         * <p>The person or merchant who initiated the transaction, or alternatively, to whom the transaction was paid.</p>
         */
        @JsonSetter(value = "payee", nulls = Nulls.SKIP)
        public Builder payee(Optional<String> payee) {
            this.payee = payee;
            return this;
        }

        public Builder payee(String payee) {
            this.payee = Optional.ofNullable(payee);
            return this;
        }

        public Builder payee(Nullable<String> payee) {
            if (payee.isNull()) {
                this.payee = null;
            } else if (payee.isEmpty()) {
                this.payee = Optional.empty();
            } else {
                this.payee = Optional.of(payee.get());
            }
            return this;
        }

        /**
         * <p>If the transaction is of type debit or credit.</p>
         * <ul>
         * <li><code>CREDIT</code> - CREDIT</li>
         * <li><code>DEBIT</code> - DEBIT</li>
         * </ul>
         */
        @JsonSetter(value = "credit_or_debit", nulls = Nulls.SKIP)
        public Builder creditOrDebit(Optional<BankFeedTransactionCreditOrDebit> creditOrDebit) {
            this.creditOrDebit = creditOrDebit;
            return this;
        }

        public Builder creditOrDebit(BankFeedTransactionCreditOrDebit creditOrDebit) {
            this.creditOrDebit = Optional.ofNullable(creditOrDebit);
            return this;
        }

        public Builder creditOrDebit(Nullable<BankFeedTransactionCreditOrDebit> creditOrDebit) {
            if (creditOrDebit.isNull()) {
                this.creditOrDebit = null;
            } else if (creditOrDebit.isEmpty()) {
                this.creditOrDebit = Optional.empty();
            } else {
                this.creditOrDebit = Optional.of(creditOrDebit.get());
            }
            return this;
        }

        /**
         * <p>The customer’s identifier for the transaction.</p>
         */
        @JsonSetter(value = "source_transaction_id", nulls = Nulls.SKIP)
        public Builder sourceTransactionId(Optional<String> sourceTransactionId) {
            this.sourceTransactionId = sourceTransactionId;
            return this;
        }

        public Builder sourceTransactionId(String sourceTransactionId) {
            this.sourceTransactionId = Optional.ofNullable(sourceTransactionId);
            return this;
        }

        public Builder sourceTransactionId(Nullable<String> sourceTransactionId) {
            if (sourceTransactionId.isNull()) {
                this.sourceTransactionId = null;
            } else if (sourceTransactionId.isEmpty()) {
                this.sourceTransactionId = Optional.empty();
            } else {
                this.sourceTransactionId = Optional.of(sourceTransactionId.get());
            }
            return this;
        }

        /**
         * <p>Indicates whether or not this object has been deleted in the third party platform. Full coverage deletion detection is a premium add-on. Native deletion detection is offered for free with limited coverage. <a href="https://docs.merge.dev/integrations/hris/supported-features/">Learn more</a>.</p>
         */
        @JsonSetter(value = "remote_was_deleted", nulls = Nulls.SKIP)
        public Builder remoteWasDeleted(Optional<Boolean> remoteWasDeleted) {
            this.remoteWasDeleted = remoteWasDeleted;
            return this;
        }

        public Builder remoteWasDeleted(Boolean remoteWasDeleted) {
            this.remoteWasDeleted = Optional.ofNullable(remoteWasDeleted);
            return this;
        }

        /**
         * <p>Whether or not this transaction has been processed by the external system. For example, NetSuite writes this field as True when the SuiteApp has processed the transaction.</p>
         */
        @JsonSetter(value = "is_processed", nulls = Nulls.SKIP)
        public Builder isProcessed(Optional<Boolean> isProcessed) {
            this.isProcessed = isProcessed;
            return this;
        }

        public Builder isProcessed(Boolean isProcessed) {
            this.isProcessed = Optional.ofNullable(isProcessed);
            return this;
        }

        public BankFeedTransaction build() {
            return new BankFeedTransaction(
                    id,
                    remoteId,
                    createdAt,
                    modifiedAt,
                    bankFeedAccount,
                    transactionDate,
                    postedDate,
                    amount,
                    description,
                    transactionType,
                    payee,
                    creditOrDebit,
                    sourceTransactionId,
                    remoteWasDeleted,
                    isProcessed,
                    additionalProperties);
        }
    }
}
