/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.accounting.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BatchObjectsResponseStatusEnum {
    public static final BatchObjectsResponseStatusEnum PARTIAL_SUCCESS =
            new BatchObjectsResponseStatusEnum(Value.PARTIAL_SUCCESS, "PARTIAL_SUCCESS");

    public static final BatchObjectsResponseStatusEnum ENQUEUED =
            new BatchObjectsResponseStatusEnum(Value.ENQUEUED, "ENQUEUED");

    public static final BatchObjectsResponseStatusEnum IN_PROGRESS =
            new BatchObjectsResponseStatusEnum(Value.IN_PROGRESS, "IN_PROGRESS");

    public static final BatchObjectsResponseStatusEnum RATE_LIMITED =
            new BatchObjectsResponseStatusEnum(Value.RATE_LIMITED, "RATE_LIMITED");

    public static final BatchObjectsResponseStatusEnum SUCCESS =
            new BatchObjectsResponseStatusEnum(Value.SUCCESS, "SUCCESS");

    public static final BatchObjectsResponseStatusEnum FAILED =
            new BatchObjectsResponseStatusEnum(Value.FAILED, "FAILED");

    private final Value value;

    private final String string;

    BatchObjectsResponseStatusEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof BatchObjectsResponseStatusEnum
                        && this.string.equals(((BatchObjectsResponseStatusEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PARTIAL_SUCCESS:
                return visitor.visitPartialSuccess();
            case ENQUEUED:
                return visitor.visitEnqueued();
            case IN_PROGRESS:
                return visitor.visitInProgress();
            case RATE_LIMITED:
                return visitor.visitRateLimited();
            case SUCCESS:
                return visitor.visitSuccess();
            case FAILED:
                return visitor.visitFailed();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BatchObjectsResponseStatusEnum valueOf(String value) {
        switch (value) {
            case "PARTIAL_SUCCESS":
                return PARTIAL_SUCCESS;
            case "ENQUEUED":
                return ENQUEUED;
            case "IN_PROGRESS":
                return IN_PROGRESS;
            case "RATE_LIMITED":
                return RATE_LIMITED;
            case "SUCCESS":
                return SUCCESS;
            case "FAILED":
                return FAILED;
            default:
                return new BatchObjectsResponseStatusEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ENQUEUED,

        IN_PROGRESS,

        PARTIAL_SUCCESS,

        SUCCESS,

        FAILED,

        RATE_LIMITED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitEnqueued();

        T visitInProgress();

        T visitPartialSuccess();

        T visitSuccess();

        T visitFailed();

        T visitRateLimited();

        T visitUnknown(String unknownType);
    }
}
