/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.accounting.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ContactsListRequestRemoteFields {
    public static final ContactsListRequestRemoteFields STATUS =
            new ContactsListRequestRemoteFields(Value.STATUS, "status");

    private final Value value;

    private final String string;

    ContactsListRequestRemoteFields(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ContactsListRequestRemoteFields
                        && this.string.equals(((ContactsListRequestRemoteFields) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case STATUS:
                return visitor.visitStatus();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ContactsListRequestRemoteFields valueOf(String value) {
        switch (value) {
            case "status":
                return STATUS;
            default:
                return new ContactsListRequestRemoteFields(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        STATUS,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitStatus();

        T visitUnknown(String unknownType);
    }
}
