/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.accounting.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ContactsListRequestStatus {
    public static final ContactsListRequestStatus ARCHIVED = new ContactsListRequestStatus(Value.ARCHIVED, "ARCHIVED");

    public static final ContactsListRequestStatus ACTIVE = new ContactsListRequestStatus(Value.ACTIVE, "ACTIVE");

    public static final ContactsListRequestStatus EMPTY = new ContactsListRequestStatus(Value.EMPTY, "");

    private final Value value;

    private final String string;

    ContactsListRequestStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ContactsListRequestStatus
                        && this.string.equals(((ContactsListRequestStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ARCHIVED:
                return visitor.visitArchived();
            case ACTIVE:
                return visitor.visitActive();
            case EMPTY:
                return visitor.visitEmpty();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ContactsListRequestStatus valueOf(String value) {
        switch (value) {
            case "ARCHIVED":
                return ARCHIVED;
            case "ACTIVE":
                return ACTIVE;
            case "":
                return EMPTY;
            default:
                return new ContactsListRequestStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        EMPTY,

        ACTIVE,

        ARCHIVED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitEmpty();

        T visitActive();

        T visitArchived();

        T visitUnknown(String unknownType);
    }
}
