/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.accounting.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreditNotesListRequestExpandItem {
    public static final CreditNotesListRequestExpandItem ACCOUNTING_PERIOD =
            new CreditNotesListRequestExpandItem(Value.ACCOUNTING_PERIOD, "accounting_period");

    public static final CreditNotesListRequestExpandItem LINE_ITEMS =
            new CreditNotesListRequestExpandItem(Value.LINE_ITEMS, "line_items");

    public static final CreditNotesListRequestExpandItem PAYMENTS =
            new CreditNotesListRequestExpandItem(Value.PAYMENTS, "payments");

    public static final CreditNotesListRequestExpandItem TRACKING_CATEGORIES =
            new CreditNotesListRequestExpandItem(Value.TRACKING_CATEGORIES, "tracking_categories");

    public static final CreditNotesListRequestExpandItem CONTACT =
            new CreditNotesListRequestExpandItem(Value.CONTACT, "contact");

    public static final CreditNotesListRequestExpandItem APPLIED_PAYMENTS =
            new CreditNotesListRequestExpandItem(Value.APPLIED_PAYMENTS, "applied_payments");

    public static final CreditNotesListRequestExpandItem COMPANY =
            new CreditNotesListRequestExpandItem(Value.COMPANY, "company");

    private final Value value;

    private final String string;

    CreditNotesListRequestExpandItem(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreditNotesListRequestExpandItem
                        && this.string.equals(((CreditNotesListRequestExpandItem) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ACCOUNTING_PERIOD:
                return visitor.visitAccountingPeriod();
            case LINE_ITEMS:
                return visitor.visitLineItems();
            case PAYMENTS:
                return visitor.visitPayments();
            case TRACKING_CATEGORIES:
                return visitor.visitTrackingCategories();
            case CONTACT:
                return visitor.visitContact();
            case APPLIED_PAYMENTS:
                return visitor.visitAppliedPayments();
            case COMPANY:
                return visitor.visitCompany();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreditNotesListRequestExpandItem valueOf(String value) {
        switch (value) {
            case "accounting_period":
                return ACCOUNTING_PERIOD;
            case "line_items":
                return LINE_ITEMS;
            case "payments":
                return PAYMENTS;
            case "tracking_categories":
                return TRACKING_CATEGORIES;
            case "contact":
                return CONTACT;
            case "applied_payments":
                return APPLIED_PAYMENTS;
            case "company":
                return COMPANY;
            default:
                return new CreditNotesListRequestExpandItem(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ACCOUNTING_PERIOD,

        APPLIED_PAYMENTS,

        COMPANY,

        CONTACT,

        LINE_ITEMS,

        PAYMENTS,

        TRACKING_CATEGORIES,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAccountingPeriod();

        T visitAppliedPayments();

        T visitCompany();

        T visitContact();

        T visitLineItems();

        T visitPayments();

        T visitTrackingCategories();

        T visitUnknown(String unknownType);
    }
}
