/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.accounting.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ItemFulfillmentsListRequestExpandItem {
    public static final ItemFulfillmentsListRequestExpandItem CUSTOMER =
            new ItemFulfillmentsListRequestExpandItem(Value.CUSTOMER, "customer");

    public static final ItemFulfillmentsListRequestExpandItem SALES_ORDER =
            new ItemFulfillmentsListRequestExpandItem(Value.SALES_ORDER, "sales_order");

    public static final ItemFulfillmentsListRequestExpandItem LINES =
            new ItemFulfillmentsListRequestExpandItem(Value.LINES, "lines");

    public static final ItemFulfillmentsListRequestExpandItem COMPANY =
            new ItemFulfillmentsListRequestExpandItem(Value.COMPANY, "company");

    private final Value value;

    private final String string;

    ItemFulfillmentsListRequestExpandItem(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ItemFulfillmentsListRequestExpandItem
                        && this.string.equals(((ItemFulfillmentsListRequestExpandItem) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CUSTOMER:
                return visitor.visitCustomer();
            case SALES_ORDER:
                return visitor.visitSalesOrder();
            case LINES:
                return visitor.visitLines();
            case COMPANY:
                return visitor.visitCompany();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ItemFulfillmentsListRequestExpandItem valueOf(String value) {
        switch (value) {
            case "customer":
                return CUSTOMER;
            case "sales_order":
                return SALES_ORDER;
            case "lines":
                return LINES;
            case "company":
                return COMPANY;
            default:
                return new ItemFulfillmentsListRequestExpandItem(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        COMPANY,

        CUSTOMER,

        LINES,

        SALES_ORDER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCompany();

        T visitCustomer();

        T visitLines();

        T visitSalesOrder();

        T visitUnknown(String unknownType);
    }
}
