/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.legacy.api.resources.crm.types;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.merge.legacy.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IgnoreCommonModelRequest.Builder.class)
public final class IgnoreCommonModelRequest {
    private final ReasonEnum reason;

    private final Optional<String> message;

    private final Map<String, Object> additionalProperties;

    private IgnoreCommonModelRequest(
            ReasonEnum reason, Optional<String> message, Map<String, Object> additionalProperties) {
        this.reason = reason;
        this.message = message;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("reason")
    public ReasonEnum getReason() {
        return reason;
    }

    @JsonProperty("message")
    public Optional<String> getMessage() {
        return message;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IgnoreCommonModelRequest && equalTo((IgnoreCommonModelRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IgnoreCommonModelRequest other) {
        return reason.equals(other.reason) && message.equals(other.message);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.reason, this.message);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ReasonStage builder() {
        return new Builder();
    }

    public interface ReasonStage {
        _FinalStage reason(@NotNull ReasonEnum reason);

        Builder from(IgnoreCommonModelRequest other);
    }

    public interface _FinalStage {
        IgnoreCommonModelRequest build();

        _FinalStage message(Optional<String> message);

        _FinalStage message(String message);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ReasonStage, _FinalStage {
        private ReasonEnum reason;

        private Optional<String> message = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(IgnoreCommonModelRequest other) {
            reason(other.getReason());
            message(other.getMessage());
            return this;
        }

        @Override
        @JsonSetter("reason")
        public _FinalStage reason(@NotNull ReasonEnum reason) {
            this.reason = reason;
            return this;
        }

        @Override
        public _FinalStage message(String message) {
            this.message = Optional.ofNullable(message);
            return this;
        }

        @Override
        @JsonSetter(value = "message", nulls = Nulls.SKIP)
        public _FinalStage message(Optional<String> message) {
            this.message = message;
            return this;
        }

        @Override
        public IgnoreCommonModelRequest build() {
            return new IgnoreCommonModelRequest(reason, message, additionalProperties);
        }
    }
}
