/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.ticketing.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.merge.api.core.Nullable;
import com.merge.api.core.NullableNonemptyFilter;
import com.merge.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Attachment.Builder.class)
public final class Attachment {
    private final Optional<String> id;

    private final Optional<String> remoteId;

    private final Optional<OffsetDateTime> createdAt;

    private final Optional<OffsetDateTime> modifiedAt;

    private final Optional<String> fileName;

    private final Optional<AttachmentTicket> ticket;

    private final Optional<String> fileUrl;

    private final Optional<String> contentType;

    private final Optional<String> uploadedBy;

    private final Optional<OffsetDateTime> remoteCreatedAt;

    private final Optional<Boolean> remoteWasDeleted;

    private final Optional<Map<String, JsonNode>> fieldMappings;

    private final Optional<List<RemoteData>> remoteData;

    private final Map<String, Object> additionalProperties;

    private Attachment(
            Optional<String> id,
            Optional<String> remoteId,
            Optional<OffsetDateTime> createdAt,
            Optional<OffsetDateTime> modifiedAt,
            Optional<String> fileName,
            Optional<AttachmentTicket> ticket,
            Optional<String> fileUrl,
            Optional<String> contentType,
            Optional<String> uploadedBy,
            Optional<OffsetDateTime> remoteCreatedAt,
            Optional<Boolean> remoteWasDeleted,
            Optional<Map<String, JsonNode>> fieldMappings,
            Optional<List<RemoteData>> remoteData,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.remoteId = remoteId;
        this.createdAt = createdAt;
        this.modifiedAt = modifiedAt;
        this.fileName = fileName;
        this.ticket = ticket;
        this.fileUrl = fileUrl;
        this.contentType = contentType;
        this.uploadedBy = uploadedBy;
        this.remoteCreatedAt = remoteCreatedAt;
        this.remoteWasDeleted = remoteWasDeleted;
        this.fieldMappings = fieldMappings;
        this.remoteData = remoteData;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return The third-party API ID of the matching object.
     */
    @JsonIgnore
    public Optional<String> getRemoteId() {
        if (remoteId == null) {
            return Optional.empty();
        }
        return remoteId;
    }

    /**
     * @return The datetime that this object was created by Merge.
     */
    @JsonProperty("created_at")
    public Optional<OffsetDateTime> getCreatedAt() {
        return createdAt;
    }

    /**
     * @return The datetime that this object was modified by Merge.
     */
    @JsonProperty("modified_at")
    public Optional<OffsetDateTime> getModifiedAt() {
        return modifiedAt;
    }

    /**
     * @return The attachment's name. It is required to include the file extension in the attachment's name.
     */
    @JsonIgnore
    public Optional<String> getFileName() {
        if (fileName == null) {
            return Optional.empty();
        }
        return fileName;
    }

    /**
     * @return The ticket associated with the attachment.
     */
    @JsonIgnore
    public Optional<AttachmentTicket> getTicket() {
        if (ticket == null) {
            return Optional.empty();
        }
        return ticket;
    }

    /**
     * @return The attachment's url. It is required to include the file extension in the file's URL.
     */
    @JsonIgnore
    public Optional<String> getFileUrl() {
        if (fileUrl == null) {
            return Optional.empty();
        }
        return fileUrl;
    }

    /**
     * @return The attachment's file format.
     */
    @JsonIgnore
    public Optional<String> getContentType() {
        if (contentType == null) {
            return Optional.empty();
        }
        return contentType;
    }

    /**
     * @return The user who uploaded the attachment.
     */
    @JsonIgnore
    public Optional<String> getUploadedBy() {
        if (uploadedBy == null) {
            return Optional.empty();
        }
        return uploadedBy;
    }

    /**
     * @return When the third party's attachment was created.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getRemoteCreatedAt() {
        if (remoteCreatedAt == null) {
            return Optional.empty();
        }
        return remoteCreatedAt;
    }

    /**
     * @return Indicates whether or not this object has been deleted in the third party platform. Full coverage deletion detection is a premium add-on. Native deletion detection is offered for free with limited coverage. <a href="https://docs.merge.dev/integrations/hris/supported-features/">Learn more</a>.
     */
    @JsonProperty("remote_was_deleted")
    public Optional<Boolean> getRemoteWasDeleted() {
        return remoteWasDeleted;
    }

    @JsonIgnore
    public Optional<Map<String, JsonNode>> getFieldMappings() {
        if (fieldMappings == null) {
            return Optional.empty();
        }
        return fieldMappings;
    }

    @JsonIgnore
    public Optional<List<RemoteData>> getRemoteData() {
        if (remoteData == null) {
            return Optional.empty();
        }
        return remoteData;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("remote_id")
    private Optional<String> _getRemoteId() {
        return remoteId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("file_name")
    private Optional<String> _getFileName() {
        return fileName;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("ticket")
    private Optional<AttachmentTicket> _getTicket() {
        return ticket;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("file_url")
    private Optional<String> _getFileUrl() {
        return fileUrl;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("content_type")
    private Optional<String> _getContentType() {
        return contentType;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("uploaded_by")
    private Optional<String> _getUploadedBy() {
        return uploadedBy;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("remote_created_at")
    private Optional<OffsetDateTime> _getRemoteCreatedAt() {
        return remoteCreatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("field_mappings")
    private Optional<Map<String, JsonNode>> _getFieldMappings() {
        return fieldMappings;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("remote_data")
    private Optional<List<RemoteData>> _getRemoteData() {
        return remoteData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Attachment && equalTo((Attachment) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Attachment other) {
        return id.equals(other.id)
                && remoteId.equals(other.remoteId)
                && createdAt.equals(other.createdAt)
                && modifiedAt.equals(other.modifiedAt)
                && fileName.equals(other.fileName)
                && ticket.equals(other.ticket)
                && fileUrl.equals(other.fileUrl)
                && contentType.equals(other.contentType)
                && uploadedBy.equals(other.uploadedBy)
                && remoteCreatedAt.equals(other.remoteCreatedAt)
                && remoteWasDeleted.equals(other.remoteWasDeleted)
                && fieldMappings.equals(other.fieldMappings)
                && remoteData.equals(other.remoteData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.remoteId,
                this.createdAt,
                this.modifiedAt,
                this.fileName,
                this.ticket,
                this.fileUrl,
                this.contentType,
                this.uploadedBy,
                this.remoteCreatedAt,
                this.remoteWasDeleted,
                this.fieldMappings,
                this.remoteData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<String> remoteId = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        private Optional<OffsetDateTime> modifiedAt = Optional.empty();

        private Optional<String> fileName = Optional.empty();

        private Optional<AttachmentTicket> ticket = Optional.empty();

        private Optional<String> fileUrl = Optional.empty();

        private Optional<String> contentType = Optional.empty();

        private Optional<String> uploadedBy = Optional.empty();

        private Optional<OffsetDateTime> remoteCreatedAt = Optional.empty();

        private Optional<Boolean> remoteWasDeleted = Optional.empty();

        private Optional<Map<String, JsonNode>> fieldMappings = Optional.empty();

        private Optional<List<RemoteData>> remoteData = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(Attachment other) {
            id(other.getId());
            remoteId(other.getRemoteId());
            createdAt(other.getCreatedAt());
            modifiedAt(other.getModifiedAt());
            fileName(other.getFileName());
            ticket(other.getTicket());
            fileUrl(other.getFileUrl());
            contentType(other.getContentType());
            uploadedBy(other.getUploadedBy());
            remoteCreatedAt(other.getRemoteCreatedAt());
            remoteWasDeleted(other.getRemoteWasDeleted());
            fieldMappings(other.getFieldMappings());
            remoteData(other.getRemoteData());
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>The third-party API ID of the matching object.</p>
         */
        @JsonSetter(value = "remote_id", nulls = Nulls.SKIP)
        public Builder remoteId(Optional<String> remoteId) {
            this.remoteId = remoteId;
            return this;
        }

        public Builder remoteId(String remoteId) {
            this.remoteId = Optional.ofNullable(remoteId);
            return this;
        }

        public Builder remoteId(Nullable<String> remoteId) {
            if (remoteId.isNull()) {
                this.remoteId = null;
            } else if (remoteId.isEmpty()) {
                this.remoteId = Optional.empty();
            } else {
                this.remoteId = Optional.of(remoteId.get());
            }
            return this;
        }

        /**
         * <p>The datetime that this object was created by Merge.</p>
         */
        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public Builder createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * <p>The datetime that this object was modified by Merge.</p>
         */
        @JsonSetter(value = "modified_at", nulls = Nulls.SKIP)
        public Builder modifiedAt(Optional<OffsetDateTime> modifiedAt) {
            this.modifiedAt = modifiedAt;
            return this;
        }

        public Builder modifiedAt(OffsetDateTime modifiedAt) {
            this.modifiedAt = Optional.ofNullable(modifiedAt);
            return this;
        }

        /**
         * <p>The attachment's name. It is required to include the file extension in the attachment's name.</p>
         */
        @JsonSetter(value = "file_name", nulls = Nulls.SKIP)
        public Builder fileName(Optional<String> fileName) {
            this.fileName = fileName;
            return this;
        }

        public Builder fileName(String fileName) {
            this.fileName = Optional.ofNullable(fileName);
            return this;
        }

        public Builder fileName(Nullable<String> fileName) {
            if (fileName.isNull()) {
                this.fileName = null;
            } else if (fileName.isEmpty()) {
                this.fileName = Optional.empty();
            } else {
                this.fileName = Optional.of(fileName.get());
            }
            return this;
        }

        /**
         * <p>The ticket associated with the attachment.</p>
         */
        @JsonSetter(value = "ticket", nulls = Nulls.SKIP)
        public Builder ticket(Optional<AttachmentTicket> ticket) {
            this.ticket = ticket;
            return this;
        }

        public Builder ticket(AttachmentTicket ticket) {
            this.ticket = Optional.ofNullable(ticket);
            return this;
        }

        public Builder ticket(Nullable<AttachmentTicket> ticket) {
            if (ticket.isNull()) {
                this.ticket = null;
            } else if (ticket.isEmpty()) {
                this.ticket = Optional.empty();
            } else {
                this.ticket = Optional.of(ticket.get());
            }
            return this;
        }

        /**
         * <p>The attachment's url. It is required to include the file extension in the file's URL.</p>
         */
        @JsonSetter(value = "file_url", nulls = Nulls.SKIP)
        public Builder fileUrl(Optional<String> fileUrl) {
            this.fileUrl = fileUrl;
            return this;
        }

        public Builder fileUrl(String fileUrl) {
            this.fileUrl = Optional.ofNullable(fileUrl);
            return this;
        }

        public Builder fileUrl(Nullable<String> fileUrl) {
            if (fileUrl.isNull()) {
                this.fileUrl = null;
            } else if (fileUrl.isEmpty()) {
                this.fileUrl = Optional.empty();
            } else {
                this.fileUrl = Optional.of(fileUrl.get());
            }
            return this;
        }

        /**
         * <p>The attachment's file format.</p>
         */
        @JsonSetter(value = "content_type", nulls = Nulls.SKIP)
        public Builder contentType(Optional<String> contentType) {
            this.contentType = contentType;
            return this;
        }

        public Builder contentType(String contentType) {
            this.contentType = Optional.ofNullable(contentType);
            return this;
        }

        public Builder contentType(Nullable<String> contentType) {
            if (contentType.isNull()) {
                this.contentType = null;
            } else if (contentType.isEmpty()) {
                this.contentType = Optional.empty();
            } else {
                this.contentType = Optional.of(contentType.get());
            }
            return this;
        }

        /**
         * <p>The user who uploaded the attachment.</p>
         */
        @JsonSetter(value = "uploaded_by", nulls = Nulls.SKIP)
        public Builder uploadedBy(Optional<String> uploadedBy) {
            this.uploadedBy = uploadedBy;
            return this;
        }

        public Builder uploadedBy(String uploadedBy) {
            this.uploadedBy = Optional.ofNullable(uploadedBy);
            return this;
        }

        public Builder uploadedBy(Nullable<String> uploadedBy) {
            if (uploadedBy.isNull()) {
                this.uploadedBy = null;
            } else if (uploadedBy.isEmpty()) {
                this.uploadedBy = Optional.empty();
            } else {
                this.uploadedBy = Optional.of(uploadedBy.get());
            }
            return this;
        }

        /**
         * <p>When the third party's attachment was created.</p>
         */
        @JsonSetter(value = "remote_created_at", nulls = Nulls.SKIP)
        public Builder remoteCreatedAt(Optional<OffsetDateTime> remoteCreatedAt) {
            this.remoteCreatedAt = remoteCreatedAt;
            return this;
        }

        public Builder remoteCreatedAt(OffsetDateTime remoteCreatedAt) {
            this.remoteCreatedAt = Optional.ofNullable(remoteCreatedAt);
            return this;
        }

        public Builder remoteCreatedAt(Nullable<OffsetDateTime> remoteCreatedAt) {
            if (remoteCreatedAt.isNull()) {
                this.remoteCreatedAt = null;
            } else if (remoteCreatedAt.isEmpty()) {
                this.remoteCreatedAt = Optional.empty();
            } else {
                this.remoteCreatedAt = Optional.of(remoteCreatedAt.get());
            }
            return this;
        }

        /**
         * <p>Indicates whether or not this object has been deleted in the third party platform. Full coverage deletion detection is a premium add-on. Native deletion detection is offered for free with limited coverage. <a href="https://docs.merge.dev/integrations/hris/supported-features/">Learn more</a>.</p>
         */
        @JsonSetter(value = "remote_was_deleted", nulls = Nulls.SKIP)
        public Builder remoteWasDeleted(Optional<Boolean> remoteWasDeleted) {
            this.remoteWasDeleted = remoteWasDeleted;
            return this;
        }

        public Builder remoteWasDeleted(Boolean remoteWasDeleted) {
            this.remoteWasDeleted = Optional.ofNullable(remoteWasDeleted);
            return this;
        }

        @JsonSetter(value = "field_mappings", nulls = Nulls.SKIP)
        public Builder fieldMappings(Optional<Map<String, JsonNode>> fieldMappings) {
            this.fieldMappings = fieldMappings;
            return this;
        }

        public Builder fieldMappings(Map<String, JsonNode> fieldMappings) {
            this.fieldMappings = Optional.ofNullable(fieldMappings);
            return this;
        }

        public Builder fieldMappings(Nullable<Map<String, JsonNode>> fieldMappings) {
            if (fieldMappings.isNull()) {
                this.fieldMappings = null;
            } else if (fieldMappings.isEmpty()) {
                this.fieldMappings = Optional.empty();
            } else {
                this.fieldMappings = Optional.of(fieldMappings.get());
            }
            return this;
        }

        @JsonSetter(value = "remote_data", nulls = Nulls.SKIP)
        public Builder remoteData(Optional<List<RemoteData>> remoteData) {
            this.remoteData = remoteData;
            return this;
        }

        public Builder remoteData(List<RemoteData> remoteData) {
            this.remoteData = Optional.ofNullable(remoteData);
            return this;
        }

        public Builder remoteData(Nullable<List<RemoteData>> remoteData) {
            if (remoteData.isNull()) {
                this.remoteData = null;
            } else if (remoteData.isEmpty()) {
                this.remoteData = Optional.empty();
            } else {
                this.remoteData = Optional.of(remoteData.get());
            }
            return this;
        }

        public Attachment build() {
            return new Attachment(
                    id,
                    remoteId,
                    createdAt,
                    modifiedAt,
                    fileName,
                    ticket,
                    fileUrl,
                    contentType,
                    uploadedBy,
                    remoteCreatedAt,
                    remoteWasDeleted,
                    fieldMappings,
                    remoteData,
                    additionalProperties);
        }
    }
}
