/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.ticketing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EffectEnum {
    public static final EffectEnum DENIED = new EffectEnum(Value.DENIED, "DENIED");

    public static final EffectEnum INHERITED = new EffectEnum(Value.INHERITED, "INHERITED");

    public static final EffectEnum ALLOWED = new EffectEnum(Value.ALLOWED, "ALLOWED");

    private final Value value;

    private final String string;

    EffectEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof EffectEnum && this.string.equals(((EffectEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DENIED:
                return visitor.visitDenied();
            case INHERITED:
                return visitor.visitInherited();
            case ALLOWED:
                return visitor.visitAllowed();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EffectEnum valueOf(String value) {
        switch (value) {
            case "DENIED":
                return DENIED;
            case "INHERITED":
                return INHERITED;
            case "ALLOWED":
                return ALLOWED;
            default:
                return new EffectEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ALLOWED,

        DENIED,

        INHERITED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAllowed();

        T visitDenied();

        T visitInherited();

        T visitUnknown(String unknownType);
    }
}
