/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.resources.filestorage.users;

import com.merge.api.core.ClientOptions;
import com.merge.api.core.RequestOptions;
import com.merge.api.resources.filestorage.types.PaginatedUserList;
import com.merge.api.resources.filestorage.types.User;
import com.merge.api.resources.filestorage.users.requests.UsersListRequest;
import com.merge.api.resources.filestorage.users.requests.UsersRetrieveRequest;
import java.util.concurrent.CompletableFuture;

public class AsyncUsersClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawUsersClient rawClient;

    public AsyncUsersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawUsersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawUsersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a list of <code>User</code> objects.
     */
    public CompletableFuture<PaginatedUserList> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Returns a list of <code>User</code> objects.
     */
    public CompletableFuture<PaginatedUserList> list(UsersListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Returns a list of <code>User</code> objects.
     */
    public CompletableFuture<PaginatedUserList> list(UsersListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>User</code> object with the given <code>id</code>.
     */
    public CompletableFuture<User> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>User</code> object with the given <code>id</code>.
     */
    public CompletableFuture<User> retrieve(String id, UsersRetrieveRequest request) {
        return this.rawClient.retrieve(id, request).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>User</code> object with the given <code>id</code>.
     */
    public CompletableFuture<User> retrieve(String id, UsersRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).thenApply(response -> response.body());
    }
}
