/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.resources.filestorage.syncstatus;

import com.merge.api.core.ClientOptions;
import com.merge.api.core.RequestOptions;
import com.merge.api.resources.filestorage.syncstatus.requests.SyncStatusListRequest;
import com.merge.api.resources.filestorage.types.PaginatedSyncStatusList;
import java.util.concurrent.CompletableFuture;

public class AsyncSyncStatusClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawSyncStatusClient rawClient;

    public AsyncSyncStatusClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawSyncStatusClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawSyncStatusClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get syncing status. Possible values: <code>DISABLED</code>, <code>DONE</code>, <code>FAILED</code>, <code>PARTIALLY_SYNCED</code>, <code>PAUSED</code>, <code>SYNCING</code>. Learn more about sync status in our <a href="https://help.merge.dev/en/articles/8184193-merge-sync-statuses">Help Center</a>.
     */
    public CompletableFuture<PaginatedSyncStatusList> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Get syncing status. Possible values: <code>DISABLED</code>, <code>DONE</code>, <code>FAILED</code>, <code>PARTIALLY_SYNCED</code>, <code>PAUSED</code>, <code>SYNCING</code>. Learn more about sync status in our <a href="https://help.merge.dev/en/articles/8184193-merge-sync-statuses">Help Center</a>.
     */
    public CompletableFuture<PaginatedSyncStatusList> list(SyncStatusListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Get syncing status. Possible values: <code>DISABLED</code>, <code>DONE</code>, <code>FAILED</code>, <code>PARTIALLY_SYNCED</code>, <code>PAUSED</code>, <code>SYNCING</code>. Learn more about sync status in our <a href="https://help.merge.dev/en/articles/8184193-merge-sync-statuses">Help Center</a>.
     */
    public CompletableFuture<PaginatedSyncStatusList> list(
            SyncStatusListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }
}
