/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.hris;

import com.merge.api.core.ClientOptions;
import com.merge.api.core.RequestOptions;
import com.merge.api.hris.types.Dependent;
import com.merge.api.hris.types.DependentsListRequest;
import com.merge.api.hris.types.DependentsRetrieveRequest;
import com.merge.api.hris.types.PaginatedDependentList;

public class DependentsClient {
    protected final ClientOptions clientOptions;

    private final RawDependentsClient rawClient;

    public DependentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawDependentsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawDependentsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a list of <code>Dependent</code> objects.
     */
    public PaginatedDependentList list() {
        return this.rawClient.list().body();
    }

    /**
     * Returns a list of <code>Dependent</code> objects.
     */
    public PaginatedDependentList list(DependentsListRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Returns a list of <code>Dependent</code> objects.
     */
    public PaginatedDependentList list(DependentsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Returns a <code>Dependent</code> object with the given <code>id</code>.
     */
    public Dependent retrieve(String id) {
        return this.rawClient.retrieve(id).body();
    }

    /**
     * Returns a <code>Dependent</code> object with the given <code>id</code>.
     */
    public Dependent retrieve(String id, DependentsRetrieveRequest request) {
        return this.rawClient.retrieve(id, request).body();
    }

    /**
     * Returns a <code>Dependent</code> object with the given <code>id</code>.
     */
    public Dependent retrieve(String id, DependentsRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).body();
    }
}
