/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.hris;

import com.merge.api.core.ClientOptions;
import com.merge.api.core.RequestOptions;
import com.merge.api.core.SyncPagingIterable;
import com.merge.api.hris.types.EmployeePayrollRun;
import com.merge.api.hris.types.EmployeePayrollRunsListRequest;
import com.merge.api.hris.types.EmployeePayrollRunsRetrieveRequest;

public class EmployeePayrollRunsClient {
    protected final ClientOptions clientOptions;

    private final RawEmployeePayrollRunsClient rawClient;

    public EmployeePayrollRunsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawEmployeePayrollRunsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawEmployeePayrollRunsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a list of <code>EmployeePayrollRun</code> objects.
     */
    public SyncPagingIterable<EmployeePayrollRun> list() {
        return this.rawClient.list().body();
    }

    /**
     * Returns a list of <code>EmployeePayrollRun</code> objects.
     */
    public SyncPagingIterable<EmployeePayrollRun> list(EmployeePayrollRunsListRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Returns a list of <code>EmployeePayrollRun</code> objects.
     */
    public SyncPagingIterable<EmployeePayrollRun> list(
            EmployeePayrollRunsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Returns an <code>EmployeePayrollRun</code> object with the given <code>id</code>.
     */
    public EmployeePayrollRun retrieve(String id) {
        return this.rawClient.retrieve(id).body();
    }

    /**
     * Returns an <code>EmployeePayrollRun</code> object with the given <code>id</code>.
     */
    public EmployeePayrollRun retrieve(String id, EmployeePayrollRunsRetrieveRequest request) {
        return this.rawClient.retrieve(id, request).body();
    }

    /**
     * Returns an <code>EmployeePayrollRun</code> object with the given <code>id</code>.
     */
    public EmployeePayrollRun retrieve(
            String id, EmployeePayrollRunsRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).body();
    }
}
