/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.ats.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.merge.api.core.Nullable;
import com.merge.api.core.NullableNonemptyFilter;
import com.merge.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ApplicationRequest.Builder.class)
public final class ApplicationRequest {
    private final Optional<ApplicationRequestCandidate> candidate;

    private final Optional<ApplicationRequestJob> job;

    private final Optional<OffsetDateTime> appliedAt;

    private final Optional<OffsetDateTime> rejectedAt;

    private final Optional<List<Optional<ApplicationRequestOffersItem>>> offers;

    private final Optional<String> source;

    private final Optional<ApplicationRequestCreditedTo> creditedTo;

    private final Optional<List<ApplicationRequestScreeningQuestionAnswersItem>> screeningQuestionAnswers;

    private final Optional<ApplicationRequestCurrentStage> currentStage;

    private final Optional<ApplicationRequestRejectReason> rejectReason;

    private final Optional<String> remoteTemplateId;

    private final Optional<Map<String, JsonNode>> integrationParams;

    private final Optional<Map<String, JsonNode>> linkedAccountParams;

    private final Map<String, Object> additionalProperties;

    private ApplicationRequest(
            Optional<ApplicationRequestCandidate> candidate,
            Optional<ApplicationRequestJob> job,
            Optional<OffsetDateTime> appliedAt,
            Optional<OffsetDateTime> rejectedAt,
            Optional<List<Optional<ApplicationRequestOffersItem>>> offers,
            Optional<String> source,
            Optional<ApplicationRequestCreditedTo> creditedTo,
            Optional<List<ApplicationRequestScreeningQuestionAnswersItem>> screeningQuestionAnswers,
            Optional<ApplicationRequestCurrentStage> currentStage,
            Optional<ApplicationRequestRejectReason> rejectReason,
            Optional<String> remoteTemplateId,
            Optional<Map<String, JsonNode>> integrationParams,
            Optional<Map<String, JsonNode>> linkedAccountParams,
            Map<String, Object> additionalProperties) {
        this.candidate = candidate;
        this.job = job;
        this.appliedAt = appliedAt;
        this.rejectedAt = rejectedAt;
        this.offers = offers;
        this.source = source;
        this.creditedTo = creditedTo;
        this.screeningQuestionAnswers = screeningQuestionAnswers;
        this.currentStage = currentStage;
        this.rejectReason = rejectReason;
        this.remoteTemplateId = remoteTemplateId;
        this.integrationParams = integrationParams;
        this.linkedAccountParams = linkedAccountParams;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The candidate applying.
     */
    @JsonIgnore
    public Optional<ApplicationRequestCandidate> getCandidate() {
        if (candidate == null) {
            return Optional.empty();
        }
        return candidate;
    }

    /**
     * @return The job being applied for.
     */
    @JsonIgnore
    public Optional<ApplicationRequestJob> getJob() {
        if (job == null) {
            return Optional.empty();
        }
        return job;
    }

    /**
     * @return When the application was submitted.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getAppliedAt() {
        if (appliedAt == null) {
            return Optional.empty();
        }
        return appliedAt;
    }

    /**
     * @return When the application was rejected.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getRejectedAt() {
        if (rejectedAt == null) {
            return Optional.empty();
        }
        return rejectedAt;
    }

    @JsonProperty("offers")
    public Optional<List<Optional<ApplicationRequestOffersItem>>> getOffers() {
        return offers;
    }

    /**
     * @return The application's source.
     */
    @JsonIgnore
    public Optional<String> getSource() {
        if (source == null) {
            return Optional.empty();
        }
        return source;
    }

    /**
     * @return The user credited for this application.
     */
    @JsonIgnore
    public Optional<ApplicationRequestCreditedTo> getCreditedTo() {
        if (creditedTo == null) {
            return Optional.empty();
        }
        return creditedTo;
    }

    @JsonProperty("screening_question_answers")
    public Optional<List<ApplicationRequestScreeningQuestionAnswersItem>> getScreeningQuestionAnswers() {
        return screeningQuestionAnswers;
    }

    /**
     * @return The application's current stage.
     */
    @JsonIgnore
    public Optional<ApplicationRequestCurrentStage> getCurrentStage() {
        if (currentStage == null) {
            return Optional.empty();
        }
        return currentStage;
    }

    /**
     * @return The application's reason for rejection.
     */
    @JsonIgnore
    public Optional<ApplicationRequestRejectReason> getRejectReason() {
        if (rejectReason == null) {
            return Optional.empty();
        }
        return rejectReason;
    }

    @JsonIgnore
    public Optional<String> getRemoteTemplateId() {
        if (remoteTemplateId == null) {
            return Optional.empty();
        }
        return remoteTemplateId;
    }

    @JsonIgnore
    public Optional<Map<String, JsonNode>> getIntegrationParams() {
        if (integrationParams == null) {
            return Optional.empty();
        }
        return integrationParams;
    }

    @JsonIgnore
    public Optional<Map<String, JsonNode>> getLinkedAccountParams() {
        if (linkedAccountParams == null) {
            return Optional.empty();
        }
        return linkedAccountParams;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("candidate")
    private Optional<ApplicationRequestCandidate> _getCandidate() {
        return candidate;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("job")
    private Optional<ApplicationRequestJob> _getJob() {
        return job;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("applied_at")
    private Optional<OffsetDateTime> _getAppliedAt() {
        return appliedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("rejected_at")
    private Optional<OffsetDateTime> _getRejectedAt() {
        return rejectedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("source")
    private Optional<String> _getSource() {
        return source;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("credited_to")
    private Optional<ApplicationRequestCreditedTo> _getCreditedTo() {
        return creditedTo;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("current_stage")
    private Optional<ApplicationRequestCurrentStage> _getCurrentStage() {
        return currentStage;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("reject_reason")
    private Optional<ApplicationRequestRejectReason> _getRejectReason() {
        return rejectReason;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("remote_template_id")
    private Optional<String> _getRemoteTemplateId() {
        return remoteTemplateId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("integration_params")
    private Optional<Map<String, JsonNode>> _getIntegrationParams() {
        return integrationParams;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("linked_account_params")
    private Optional<Map<String, JsonNode>> _getLinkedAccountParams() {
        return linkedAccountParams;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ApplicationRequest && equalTo((ApplicationRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ApplicationRequest other) {
        return candidate.equals(other.candidate)
                && job.equals(other.job)
                && appliedAt.equals(other.appliedAt)
                && rejectedAt.equals(other.rejectedAt)
                && offers.equals(other.offers)
                && source.equals(other.source)
                && creditedTo.equals(other.creditedTo)
                && screeningQuestionAnswers.equals(other.screeningQuestionAnswers)
                && currentStage.equals(other.currentStage)
                && rejectReason.equals(other.rejectReason)
                && remoteTemplateId.equals(other.remoteTemplateId)
                && integrationParams.equals(other.integrationParams)
                && linkedAccountParams.equals(other.linkedAccountParams);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.candidate,
                this.job,
                this.appliedAt,
                this.rejectedAt,
                this.offers,
                this.source,
                this.creditedTo,
                this.screeningQuestionAnswers,
                this.currentStage,
                this.rejectReason,
                this.remoteTemplateId,
                this.integrationParams,
                this.linkedAccountParams);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ApplicationRequestCandidate> candidate = Optional.empty();

        private Optional<ApplicationRequestJob> job = Optional.empty();

        private Optional<OffsetDateTime> appliedAt = Optional.empty();

        private Optional<OffsetDateTime> rejectedAt = Optional.empty();

        private Optional<List<Optional<ApplicationRequestOffersItem>>> offers = Optional.empty();

        private Optional<String> source = Optional.empty();

        private Optional<ApplicationRequestCreditedTo> creditedTo = Optional.empty();

        private Optional<List<ApplicationRequestScreeningQuestionAnswersItem>> screeningQuestionAnswers =
                Optional.empty();

        private Optional<ApplicationRequestCurrentStage> currentStage = Optional.empty();

        private Optional<ApplicationRequestRejectReason> rejectReason = Optional.empty();

        private Optional<String> remoteTemplateId = Optional.empty();

        private Optional<Map<String, JsonNode>> integrationParams = Optional.empty();

        private Optional<Map<String, JsonNode>> linkedAccountParams = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ApplicationRequest other) {
            candidate(other.getCandidate());
            job(other.getJob());
            appliedAt(other.getAppliedAt());
            rejectedAt(other.getRejectedAt());
            offers(other.getOffers());
            source(other.getSource());
            creditedTo(other.getCreditedTo());
            screeningQuestionAnswers(other.getScreeningQuestionAnswers());
            currentStage(other.getCurrentStage());
            rejectReason(other.getRejectReason());
            remoteTemplateId(other.getRemoteTemplateId());
            integrationParams(other.getIntegrationParams());
            linkedAccountParams(other.getLinkedAccountParams());
            return this;
        }

        /**
         * <p>The candidate applying.</p>
         */
        @JsonSetter(value = "candidate", nulls = Nulls.SKIP)
        public Builder candidate(Optional<ApplicationRequestCandidate> candidate) {
            this.candidate = candidate;
            return this;
        }

        public Builder candidate(ApplicationRequestCandidate candidate) {
            this.candidate = Optional.ofNullable(candidate);
            return this;
        }

        public Builder candidate(Nullable<ApplicationRequestCandidate> candidate) {
            if (candidate.isNull()) {
                this.candidate = null;
            } else if (candidate.isEmpty()) {
                this.candidate = Optional.empty();
            } else {
                this.candidate = Optional.of(candidate.get());
            }
            return this;
        }

        /**
         * <p>The job being applied for.</p>
         */
        @JsonSetter(value = "job", nulls = Nulls.SKIP)
        public Builder job(Optional<ApplicationRequestJob> job) {
            this.job = job;
            return this;
        }

        public Builder job(ApplicationRequestJob job) {
            this.job = Optional.ofNullable(job);
            return this;
        }

        public Builder job(Nullable<ApplicationRequestJob> job) {
            if (job.isNull()) {
                this.job = null;
            } else if (job.isEmpty()) {
                this.job = Optional.empty();
            } else {
                this.job = Optional.of(job.get());
            }
            return this;
        }

        /**
         * <p>When the application was submitted.</p>
         */
        @JsonSetter(value = "applied_at", nulls = Nulls.SKIP)
        public Builder appliedAt(Optional<OffsetDateTime> appliedAt) {
            this.appliedAt = appliedAt;
            return this;
        }

        public Builder appliedAt(OffsetDateTime appliedAt) {
            this.appliedAt = Optional.ofNullable(appliedAt);
            return this;
        }

        public Builder appliedAt(Nullable<OffsetDateTime> appliedAt) {
            if (appliedAt.isNull()) {
                this.appliedAt = null;
            } else if (appliedAt.isEmpty()) {
                this.appliedAt = Optional.empty();
            } else {
                this.appliedAt = Optional.of(appliedAt.get());
            }
            return this;
        }

        /**
         * <p>When the application was rejected.</p>
         */
        @JsonSetter(value = "rejected_at", nulls = Nulls.SKIP)
        public Builder rejectedAt(Optional<OffsetDateTime> rejectedAt) {
            this.rejectedAt = rejectedAt;
            return this;
        }

        public Builder rejectedAt(OffsetDateTime rejectedAt) {
            this.rejectedAt = Optional.ofNullable(rejectedAt);
            return this;
        }

        public Builder rejectedAt(Nullable<OffsetDateTime> rejectedAt) {
            if (rejectedAt.isNull()) {
                this.rejectedAt = null;
            } else if (rejectedAt.isEmpty()) {
                this.rejectedAt = Optional.empty();
            } else {
                this.rejectedAt = Optional.of(rejectedAt.get());
            }
            return this;
        }

        @JsonSetter(value = "offers", nulls = Nulls.SKIP)
        public Builder offers(Optional<List<Optional<ApplicationRequestOffersItem>>> offers) {
            this.offers = offers;
            return this;
        }

        public Builder offers(List<Optional<ApplicationRequestOffersItem>> offers) {
            this.offers = Optional.ofNullable(offers);
            return this;
        }

        /**
         * <p>The application's source.</p>
         */
        @JsonSetter(value = "source", nulls = Nulls.SKIP)
        public Builder source(Optional<String> source) {
            this.source = source;
            return this;
        }

        public Builder source(String source) {
            this.source = Optional.ofNullable(source);
            return this;
        }

        public Builder source(Nullable<String> source) {
            if (source.isNull()) {
                this.source = null;
            } else if (source.isEmpty()) {
                this.source = Optional.empty();
            } else {
                this.source = Optional.of(source.get());
            }
            return this;
        }

        /**
         * <p>The user credited for this application.</p>
         */
        @JsonSetter(value = "credited_to", nulls = Nulls.SKIP)
        public Builder creditedTo(Optional<ApplicationRequestCreditedTo> creditedTo) {
            this.creditedTo = creditedTo;
            return this;
        }

        public Builder creditedTo(ApplicationRequestCreditedTo creditedTo) {
            this.creditedTo = Optional.ofNullable(creditedTo);
            return this;
        }

        public Builder creditedTo(Nullable<ApplicationRequestCreditedTo> creditedTo) {
            if (creditedTo.isNull()) {
                this.creditedTo = null;
            } else if (creditedTo.isEmpty()) {
                this.creditedTo = Optional.empty();
            } else {
                this.creditedTo = Optional.of(creditedTo.get());
            }
            return this;
        }

        @JsonSetter(value = "screening_question_answers", nulls = Nulls.SKIP)
        public Builder screeningQuestionAnswers(
                Optional<List<ApplicationRequestScreeningQuestionAnswersItem>> screeningQuestionAnswers) {
            this.screeningQuestionAnswers = screeningQuestionAnswers;
            return this;
        }

        public Builder screeningQuestionAnswers(
                List<ApplicationRequestScreeningQuestionAnswersItem> screeningQuestionAnswers) {
            this.screeningQuestionAnswers = Optional.ofNullable(screeningQuestionAnswers);
            return this;
        }

        /**
         * <p>The application's current stage.</p>
         */
        @JsonSetter(value = "current_stage", nulls = Nulls.SKIP)
        public Builder currentStage(Optional<ApplicationRequestCurrentStage> currentStage) {
            this.currentStage = currentStage;
            return this;
        }

        public Builder currentStage(ApplicationRequestCurrentStage currentStage) {
            this.currentStage = Optional.ofNullable(currentStage);
            return this;
        }

        public Builder currentStage(Nullable<ApplicationRequestCurrentStage> currentStage) {
            if (currentStage.isNull()) {
                this.currentStage = null;
            } else if (currentStage.isEmpty()) {
                this.currentStage = Optional.empty();
            } else {
                this.currentStage = Optional.of(currentStage.get());
            }
            return this;
        }

        /**
         * <p>The application's reason for rejection.</p>
         */
        @JsonSetter(value = "reject_reason", nulls = Nulls.SKIP)
        public Builder rejectReason(Optional<ApplicationRequestRejectReason> rejectReason) {
            this.rejectReason = rejectReason;
            return this;
        }

        public Builder rejectReason(ApplicationRequestRejectReason rejectReason) {
            this.rejectReason = Optional.ofNullable(rejectReason);
            return this;
        }

        public Builder rejectReason(Nullable<ApplicationRequestRejectReason> rejectReason) {
            if (rejectReason.isNull()) {
                this.rejectReason = null;
            } else if (rejectReason.isEmpty()) {
                this.rejectReason = Optional.empty();
            } else {
                this.rejectReason = Optional.of(rejectReason.get());
            }
            return this;
        }

        @JsonSetter(value = "remote_template_id", nulls = Nulls.SKIP)
        public Builder remoteTemplateId(Optional<String> remoteTemplateId) {
            this.remoteTemplateId = remoteTemplateId;
            return this;
        }

        public Builder remoteTemplateId(String remoteTemplateId) {
            this.remoteTemplateId = Optional.ofNullable(remoteTemplateId);
            return this;
        }

        public Builder remoteTemplateId(Nullable<String> remoteTemplateId) {
            if (remoteTemplateId.isNull()) {
                this.remoteTemplateId = null;
            } else if (remoteTemplateId.isEmpty()) {
                this.remoteTemplateId = Optional.empty();
            } else {
                this.remoteTemplateId = Optional.of(remoteTemplateId.get());
            }
            return this;
        }

        @JsonSetter(value = "integration_params", nulls = Nulls.SKIP)
        public Builder integrationParams(Optional<Map<String, JsonNode>> integrationParams) {
            this.integrationParams = integrationParams;
            return this;
        }

        public Builder integrationParams(Map<String, JsonNode> integrationParams) {
            this.integrationParams = Optional.ofNullable(integrationParams);
            return this;
        }

        public Builder integrationParams(Nullable<Map<String, JsonNode>> integrationParams) {
            if (integrationParams.isNull()) {
                this.integrationParams = null;
            } else if (integrationParams.isEmpty()) {
                this.integrationParams = Optional.empty();
            } else {
                this.integrationParams = Optional.of(integrationParams.get());
            }
            return this;
        }

        @JsonSetter(value = "linked_account_params", nulls = Nulls.SKIP)
        public Builder linkedAccountParams(Optional<Map<String, JsonNode>> linkedAccountParams) {
            this.linkedAccountParams = linkedAccountParams;
            return this;
        }

        public Builder linkedAccountParams(Map<String, JsonNode> linkedAccountParams) {
            this.linkedAccountParams = Optional.ofNullable(linkedAccountParams);
            return this;
        }

        public Builder linkedAccountParams(Nullable<Map<String, JsonNode>> linkedAccountParams) {
            if (linkedAccountParams.isNull()) {
                this.linkedAccountParams = null;
            } else if (linkedAccountParams.isEmpty()) {
                this.linkedAccountParams = Optional.empty();
            } else {
                this.linkedAccountParams = Optional.of(linkedAccountParams.get());
            }
            return this;
        }

        public ApplicationRequest build() {
            return new ApplicationRequest(
                    candidate,
                    job,
                    appliedAt,
                    rejectedAt,
                    offers,
                    source,
                    creditedTo,
                    screeningQuestionAnswers,
                    currentStage,
                    rejectReason,
                    remoteTemplateId,
                    integrationParams,
                    linkedAccountParams,
                    additionalProperties);
        }
    }
}
