/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.ats.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum VisibilityEnum {
    ADMIN_ONLY("ADMIN_ONLY"),

    PUBLIC("PUBLIC"),

    PRIVATE("PRIVATE");

    private final String value;

    VisibilityEnum(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
