/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.accounting;

import com.merge.api.accounting.types.CreditNote;
import com.merge.api.accounting.types.CreditNoteEndpointRequest;
import com.merge.api.accounting.types.CreditNoteResponse;
import com.merge.api.accounting.types.CreditNotesListRequest;
import com.merge.api.accounting.types.CreditNotesRetrieveRequest;
import com.merge.api.accounting.types.MetaResponse;
import com.merge.api.core.ClientOptions;
import com.merge.api.core.RequestOptions;
import com.merge.api.core.SyncPagingIterable;
import java.util.concurrent.CompletableFuture;

public class AsyncCreditNotesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawCreditNotesClient rawClient;

    public AsyncCreditNotesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawCreditNotesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawCreditNotesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a list of <code>CreditNote</code> objects.
     */
    public CompletableFuture<SyncPagingIterable<CreditNote>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Returns a list of <code>CreditNote</code> objects.
     */
    public CompletableFuture<SyncPagingIterable<CreditNote>> list(CreditNotesListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Returns a list of <code>CreditNote</code> objects.
     */
    public CompletableFuture<SyncPagingIterable<CreditNote>> list(
            CreditNotesListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Creates a <code>CreditNote</code> object with the given values.
     */
    public CompletableFuture<CreditNoteResponse> create(CreditNoteEndpointRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Creates a <code>CreditNote</code> object with the given values.
     */
    public CompletableFuture<CreditNoteResponse> create(
            CreditNoteEndpointRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>CreditNote</code> object with the given <code>id</code>.
     */
    public CompletableFuture<CreditNote> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>CreditNote</code> object with the given <code>id</code>.
     */
    public CompletableFuture<CreditNote> retrieve(String id, CreditNotesRetrieveRequest request) {
        return this.rawClient.retrieve(id, request).thenApply(response -> response.body());
    }

    /**
     * Returns a <code>CreditNote</code> object with the given <code>id</code>.
     */
    public CompletableFuture<CreditNote> retrieve(
            String id, CreditNotesRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns metadata for <code>CreditNote</code> POSTs.
     */
    public CompletableFuture<MetaResponse> metaPostRetrieve() {
        return this.rawClient.metaPostRetrieve().thenApply(response -> response.body());
    }

    /**
     * Returns metadata for <code>CreditNote</code> POSTs.
     */
    public CompletableFuture<MetaResponse> metaPostRetrieve(RequestOptions requestOptions) {
        return this.rawClient.metaPostRetrieve(requestOptions).thenApply(response -> response.body());
    }
}
