/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.accounting;

import com.merge.api.accounting.types.MetaResponse;
import com.merge.api.accounting.types.VendorCredit;
import com.merge.api.accounting.types.VendorCreditEndpointRequest;
import com.merge.api.accounting.types.VendorCreditResponse;
import com.merge.api.accounting.types.VendorCreditsListRequest;
import com.merge.api.accounting.types.VendorCreditsRetrieveRequest;
import com.merge.api.core.ClientOptions;
import com.merge.api.core.RequestOptions;
import com.merge.api.core.SyncPagingIterable;

public class VendorCreditsClient {
    protected final ClientOptions clientOptions;

    private final RawVendorCreditsClient rawClient;

    public VendorCreditsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawVendorCreditsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawVendorCreditsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a list of <code>VendorCredit</code> objects.
     */
    public SyncPagingIterable<VendorCredit> list() {
        return this.rawClient.list().body();
    }

    /**
     * Returns a list of <code>VendorCredit</code> objects.
     */
    public SyncPagingIterable<VendorCredit> list(VendorCreditsListRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Returns a list of <code>VendorCredit</code> objects.
     */
    public SyncPagingIterable<VendorCredit> list(VendorCreditsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Creates a <code>VendorCredit</code> object with the given values.
     */
    public VendorCreditResponse create(VendorCreditEndpointRequest request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Creates a <code>VendorCredit</code> object with the given values.
     */
    public VendorCreditResponse create(VendorCreditEndpointRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    /**
     * Returns a <code>VendorCredit</code> object with the given <code>id</code>.
     */
    public VendorCredit retrieve(String id) {
        return this.rawClient.retrieve(id).body();
    }

    /**
     * Returns a <code>VendorCredit</code> object with the given <code>id</code>.
     */
    public VendorCredit retrieve(String id, VendorCreditsRetrieveRequest request) {
        return this.rawClient.retrieve(id, request).body();
    }

    /**
     * Returns a <code>VendorCredit</code> object with the given <code>id</code>.
     */
    public VendorCredit retrieve(String id, VendorCreditsRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).body();
    }

    /**
     * Returns metadata for <code>VendorCredit</code> POSTs.
     */
    public MetaResponse metaPostRetrieve() {
        return this.rawClient.metaPostRetrieve().body();
    }

    /**
     * Returns metadata for <code>VendorCredit</code> POSTs.
     */
    public MetaResponse metaPostRetrieve(RequestOptions requestOptions) {
        return this.rawClient.metaPostRetrieve(requestOptions).body();
    }
}
