/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.merge.api.resources.accounting.contacts.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ContactsRetrieveRequestExpand {
    ADDRESSES("addresses"),

    ADDRESSES_COMPANY("addresses,company"),

    ADDRESSES_PHONE_NUMBERS("addresses,phone_numbers"),

    ADDRESSES_PHONE_NUMBERS_COMPANY("addresses,phone_numbers,company"),

    COMPANY("company"),

    PHONE_NUMBERS("phone_numbers"),

    PHONE_NUMBERS_COMPANY("phone_numbers,company");

    private final String value;

    ContactsRetrieveRequestExpand(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
