name: ci

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        id: setup-jre
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64

      - name: Compile
        run: ./gradlew compileJava

  test:
    needs: [ compile ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        id: setup-jre
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64

      - name: Test
        run: ./gradlew test
        env:
          MERGE_API_KEY_ATS: ${{ secrets.MERGE_API_KEY_ATS }}
          MERGE_ACCOUNT_TOKEN_ATS: ${{ secrets.MERGE_ACCOUNT_TOKEN_ATS }}
          MERGE_API_KEY_CHAT: ${{ secrets.MERGE_API_KEY_CHAT }}
          MERGE_ACCOUNT_TOKEN_CHAT: ${{ secrets.MERGE_ACCOUNT_TOKEN_CHAT }}
          MERGE_API_KEY_CRM: ${{ secrets.MERGE_API_KEY_CRM }}
          MERGE_ACCOUNT_TOKEN_CRM: ${{ secrets.MERGE_ACCOUNT_TOKEN_CRM }}
          MERGE_API_KEY_FILESTORAGE: ${{ secrets.MERGE_API_KEY_FILESTORAGE }}
          MERGE_ACCOUNT_TOKEN_FILESTORAGE: ${{ secrets.MERGE_ACCOUNT_TOKEN_FILESTORAGE }}
          MERGE_API_KEY_HRIS: ${{ secrets.MERGE_API_KEY_HRIS }}
          MERGE_ACCOUNT_TOKEN_HRIS: ${{ secrets.MERGE_ACCOUNT_TOKEN_HRIS }}
          MERGE_API_KEY_KNOWLEDGEBASE: ${{ secrets.MERGE_API_KEY_KNOWLEDGEBASE }}
          MERGE_ACCOUNT_TOKEN_KNOWLEDGEBASE: ${{ secrets.MERGE_ACCOUNT_TOKEN_KNOWLEDGEBASE }}
          MERGE_API_KEY_TICKETING: ${{ secrets.MERGE_API_KEY_TICKETING }}
          MERGE_ACCOUNT_TOKEN_TICKETING: ${{ secrets.MERGE_ACCOUNT_TOKEN_TICKETING }}

  publish:
    needs: [ compile, test ]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        id: setup-jre
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64

      - name: Publish to maven
        run: |
          ./gradlew sonatypeCentralUpload
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_PUBLISH_REGISTRY_URL: "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
          MAVEN_SIGNATURE_KID: ${{ secrets.MAVEN_SIGNATURE_KID }}
          MAVEN_SIGNATURE_SECRET_KEY: ${{ secrets.MAVEN_SIGNATURE_SECRET_KEY }}
          MAVEN_SIGNATURE_PASSWORD: ${{ secrets.MAVEN_SIGNATURE_PASSWORD }}
          MERGE_API_KEY_FILESTORAGE: ${{ secrets.MERGE_API_KEY_FILESTORAGE }}
          MERGE_ACCOUNT_TOKEN_FILESTORAGE: ${{ secrets.MERGE_ACCOUNT_TOKEN_FILESTORAGE }}
          
